In [53]:
###################################################
# Rating Products
###################################################

# - Average
# - Time-Based Weighted Average
# - User-Based Weighted Average
# - Weighted Rating

In [54]:

############################################
# Uygulama: Kullanıcı ve Zaman Ağırlıklı Kurs Puanı Hesaplama
############################################

In [55]:
import pandas as pd
import math
import scipy.stats as st
from sklearn.preprocessing import MinMaxScaler

In [56]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 500)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [57]:
# (50+ Saat) Python A-Z™: Veri Bilimi ve Machine Learning
# Puan: 4.8 (4.764925)
# Toplam Puan: 4611
# Puan Yüzdeleri: 75, 20, 4, 1, <1
# Yaklaşık Sayısal Karşılıkları: 3458, 922, 184, 46, 6

In [58]:
df = pd.read_csv("course_reviews.csv")

In [59]:
df.head()

   Rating            Timestamp             Enrolled  Progress  Questions Asked  Questions Answered
0 5.00000  2021-02-05 07:45:55  2021-01-25 15:12:08   5.00000          0.00000             0.00000
1 5.00000  2021-02-04 21:05:32  2021-02-04 20:43:40   1.00000          0.00000             0.00000
2 4.50000  2021-02-04 20:34:03  2019-07-04 23:23:27   1.00000          0.00000             0.00000
3 5.00000  2021-02-04 16:56:28  2021-02-04 14:41:29  10.00000          0.00000             0.00000
4 4.00000  2021-02-04 15:00:24  2020-10-13 03:10:07  10.00000          0.00000             0.00000

In [92]:
df.shape 
# kaç tane değerlendirme vardır?

(4323, 7)

In [93]:
print(df)

      Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  days
0    5.00000 2021-02-05 07:45:55  2021-01-25 15:12:08   5.00000          0.00000             0.00000     4
1    5.00000 2021-02-04 21:05:32  2021-02-04 20:43:40   1.00000          0.00000             0.00000     5
2    4.50000 2021-02-04 20:34:03  2019-07-04 23:23:27   1.00000          0.00000             0.00000     5
3    5.00000 2021-02-04 16:56:28  2021-02-04 14:41:29  10.00000          0.00000             0.00000     5
4    4.00000 2021-02-04 15:00:24  2020-10-13 03:10:07  10.00000          0.00000             0.00000     5
5    4.00000 2021-02-04 12:42:36  2021-02-01 15:40:13   1.00000          0.00000             0.00000     5
6    5.00000 2021-02-04 12:25:30  2020-11-30 19:23:54  85.00000          0.00000             4.00000     5
7    4.50000 2021-02-04 11:13:15  2021-01-08 08:05:42  10.00000          0.00000             0.00000     5
8    5.00000 2021-02-04 08:59:53  2021-02-02 18:14:49   1.00000          0.00000             0.00000     5
9    5.00000 2021-02-03 22:40:04  2020-08-01 22:30:42  35.00000          0.00000             0.00000     6
10   5.00000 2021-02-03 21:26:02  2021-02-01 09:54:49   5.00000          0.00000             0.00000     6
11   5.00000 2021-02-03 21:14:25  2021-02-01 18:45:00   1.00000          0.00000             0.00000     6
12   5.00000 2021-02-03 20:55:19  2021-02-03 20:00:04  10.00000          0.00000             0.00000     6
13   3.00000 2021-02-03 19:16:45  2021-02-03 18:42:21   1.00000          0.00000             0.00000     6
14   5.00000 2021-02-03 19:08:33  2020-03-29 09:07:41  93.00000          1.00000             0.00000     6
15   5.00000 2021-02-03 18:57:11  2020-03-19 19:28:43   1.00000          0.00000             0.00000     6
16   2.50000 2021-02-03 18:56:58  2021-02-01 09:23:31   5.00000          0.00000             0.00000     6
17   5.00000 2021-02-03 17:21:45  2021-01-28 20:46:12   5.00000          0.00000             0.00000     6
18   5.00000 2021-02-03 17:12:26  2019-07-25 08:04:26  35.00000          0.00000             0.00000     6
19   5.00000 2021-02-03 16:13:36  2021-02-02 07:15:55   5.00000          0.00000             0.00000     6
20   4.00000 2021-02-02 23:55:23  2021-02-02 17:47:41   1.00000          0.00000             0.00000     7
21   5.00000 2021-02-02 22:34:25  2021-01-19 22:29:49   5.00000          0.00000             0.00000     7
22   5.00000 2021-02-02 21:59:49  2021-01-03 19:42:39  35.00000          0.00000             0.00000     7
23   5.00000 2021-02-02 18:00:59  2021-01-27 13:11:18   1.00000          0.00000             0.00000     7
24   5.00000 2021-02-02 16:29:58  2021-02-02 16:10:52  15.00000          0.00000             0.00000     7
25   5.00000 2021-02-02 14:30:03  2020-04-04 22:14:15  25.00000          0.00000             0.00000     7
26   5.00000 2021-02-02 12:54:25  2021-02-02 09:07:03  15.00000          0.00000             0.00000     7
27   5.00000 2021-02-02 12:02:59  2020-09-20 12:26:30   1.00000          0.00000             0.00000     7
28   5.00000 2021-02-02 11:58:42  2021-02-02 10:07:22  20.00000          0.00000             0.00000     7
29   5.00000 2021-02-02 10:47:54  2020-08-20 19:14:01   5.00000          0.00000             0.00000     7
30   5.00000 2021-02-02 04:58:56  2021-01-31 14:58:49  15.00000          0.00000             0.00000     7
31   5.00000 2021-02-01 21:27:36  2021-01-24 17:58:23  65.00000          0.00000             0.00000     8
32   5.00000 2021-02-01 19:27:59  2021-02-01 12:08:22   1.00000          0.00000             0.00000     8
33   4.50000 2021-02-01 13:09:17  2021-02-01 11:14:17  10.00000          0.00000             0.00000     8
34   5.00000 2021-02-01 12:16:46  2021-02-01 06:15:18  40.00000          0.00000             0.00000     8
35   4.50000 2021-02-01 09:29:56  2021-01-29 08:29:31  15.00000          0.00000             0.00000     8
36   5.00000 2021-02-01 07:57:43  2020-11-22 16:09:36   1.00000          0.00000             0.00000     8
37   5.00000 2021-02-01 06:03:40  2021-01-30 10:23:03   1.00000          0.00000             0.00000     8
38   5.00000 2021-01-31 21:45:28  2021-01-31 21:29:47   1.00000          0.00000             0.00000     9
39   5.00000 2021-01-31 20:52:42  2019-11-18 11:37:06   0.00000          0.00000             0.00000     9
40   3.50000 2021-01-31 19:48:51  2020-12-21 16:29:26  20.00000          0.00000             0.00000     9
41   4.50000 2021-01-31 19:34:20  2021-01-07 23:14:52   5.00000          0.00000             0.00000     9
42   5.00000 2021-01-31 18:59:27  2021-01-13 09:37:26   5.00000          0.00000             0.00000     9
43   3.50000 2021-01-31 18:07:01  2021-01-25 10:17:43   1.00000          0.00000             0.00000     9
44   5.00000 2021-01-31 16:02:14  2021-01-06 10:56:43  35.00000          0.00000             0.00000     9
45   5.00000 2021-01-31 15:45:39  2021-01-30 12:58:11  15.00000          0.00000             0.00000     9
46   4.50000 2021-01-31 15:23:46  2019-09-26 09:11:42   1.00000          0.00000             0.00000     9
47   5.00000 2021-01-31 14:13:32  2021-01-31 11:01:52  10.00000          0.00000             0.00000     9
48   4.50000 2021-01-31 11:23:24  2021-01-18 20:24:40  20.00000          0.00000             0.00000     9
49   5.00000 2021-01-31 08:48:53  2020-04-05 03:00:25   5.00000          0.00000             0.00000     9
50   5.00000 2021-01-31 08:05:53  2020-06-19 09:33:06  15.00000          0.00000             0.00000     9
51   5.00000 2021-01-30 22:17:08  2020-12-20 14:12:51  15.00000          0.00000             0.00000    10
52   5.00000 2021-01-30 18:47:09  2020-12-02 13:50:48  10.00000          0.00000             0.00000    10
53   4.00000 2021-01-30 18:00:45  2021-01-30 15:57:15   5.00000          0.00000             0.00000    10
54   5.00000 2021-01-30 17:46:47  2020-12-11 18:14:02  15.00000          0.00000             0.00000    10
55   5.00000 2021-01-30 16:57:13  2021-01-25 21:45:33  25.00000          0.00000             0.00000    10
56   5.00000 2021-01-30 16:25:44  2020-12-19 14:24:20  10.00000          0.00000             0.00000    10
57   3.00000 2021-01-30 13:44:07  2021-01-30 13:29:10   5.00000          0.00000             0.00000    10
58   5.00000 2021-01-30 12:35:03  2021-01-29 15:04:39  20.00000          0.00000             0.00000    10
59   5.00000 2021-01-30 12:10:22  2021-01-08 13:01:12  10.00000          0.00000             0.00000    10
60   5.00000 2021-01-30 11:45:02  2020-10-01 22:02:51  10.00000          0.00000             0.00000    10
61   5.00000 2021-01-30 11:28:26  2021-01-28 11:56:46  25.00000          0.00000             0.00000    10
62   5.00000 2021-01-30 10:19:14  2021-01-27 17:39:07  10.00000          0.00000             0.00000    10
63   5.00000 2021-01-29 22:30:04  2021-01-25 11:14:11  12.00000          0.00000             0.00000    11
64   5.00000 2021-01-29 20:57:29  2021-01-25 12:44:46   5.00000          0.00000             0.00000    11
65   4.00000 2021-01-29 19:51:08  2021-01-29 15:07:15  10.00000          0.00000             0.00000    11
66   5.00000 2021-01-29 18:07:02  2020-10-21 14:07:39  15.00000          0.00000             0.00000    11
67   5.00000 2021-01-29 17:54:38  2021-01-24 19:57:27  40.00000          0.00000             0.00000    11
68   5.00000 2021-01-29 15:52:18  2021-01-29 14:50:13  10.00000          0.00000             0.00000    11
69   5.00000 2021-01-29 13:50:57  2021-01-25 12:33:50   5.00000          0.00000             0.00000    11
70   5.00000 2021-01-29 13:38:44  2020-11-18 12:17:20  25.00000          0.00000             0.00000    11
71   3.50000 2021-01-29 11:36:47  2021-01-29 07:34:41  10.00000          1.00000             0.00000    11
72   4.50000 2021-01-29 11:12:09  2021-01-29 10:48:00  30.00000          0.00000             0.00000    11
73   5.00000 2021-01-29 07:49:51  2020-12-24 09:02:22   1.00000          0.00000             0.00000    11
74   5.00000 2021-01-29 06:34:40  2020-12-11 15:27:55  25.00000          0.00000             0.00000    11
75   4.50000 2021-01-28 20:17:56  2020-08-21 05:03:49   5.00000          0.00000             0.00000    12
76   5.00000 2021-01-28 17:33:55  2020-12-16 16:24:54  10.00000          0.00000             0.00000    12
77   5.00000 2021-01-28 10:09:21  2021-01-27 08:43:49   1.00000          0.00000             0.00000    12
78   5.00000 2021-01-28 08:35:46  2020-12-01 15:11:04   5.00000          0.00000             0.00000    12
79   5.00000 2021-01-27 22:36:15  2021-01-25 12:45:43  25.00000          0.00000             0.00000    13
80   5.00000 2021-01-27 22:25:12  2021-01-01 16:29:47   1.00000          0.00000             0.00000    13
81   5.00000 2021-01-27 21:25:43  2021-01-22 13:20:49  50.00000          0.00000             0.00000    13
82   4.00000 2021-01-27 20:46:02  2021-01-27 20:29:57  35.00000          0.00000             0.00000    13
83   5.00000 2021-01-27 19:20:43  2020-12-21 14:59:05  15.00000          0.00000             0.00000    13
84   4.00000 2021-01-27 18:56:24  2021-01-21 18:29:24  20.00000          0.00000             0.00000    13
85   5.00000 2021-01-27 17:21:08  2021-01-19 16:25:49   5.00000          0.00000             0.00000    13
86   5.00000 2021-01-27 14:16:50  2020-02-27 18:19:16  30.00000          0.00000             0.00000    13
87   5.00000 2021-01-27 09:01:39  2021-01-20 15:02:50  20.00000          0.00000             0.00000    13
88   5.00000 2021-01-27 07:19:53  2021-01-05 08:30:51  20.00000          0.00000             0.00000    13
89   4.50000 2021-01-26 20:35:29  2021-01-26 14:48:57  15.00000          1.00000             0.00000    14
90   5.00000 2021-01-26 20:31:50  2019-11-16 07:51:59  45.00000          0.00000             0.00000    14
91   5.00000 2021-01-26 18:21:17  2020-12-01 19:33:38  30.00000          0.00000             0.00000    14
92   5.00000 2021-01-26 12:46:00  2020-12-29 07:29:58   5.00000          0.00000             0.00000    14
93   5.00000 2021-01-26 11:36:24  2020-01-08 12:52:26  40.00000          0.00000             0.00000    14
94   4.00000 2021-01-26 11:10:07  2020-11-05 11:06:13  15.00000          0.00000             0.00000    14
95   5.00000 2021-01-26 11:06:34  2021-01-01 11:27:34  20.00000          0.00000             0.00000    14
96   5.00000 2021-01-26 09:16:21  2020-11-30 19:35:46   1.00000          0.00000             0.00000    14
97   2.00000 2021-01-26 07:56:03  2020-03-23 16:51:55   5.00000          0.00000             0.00000    14
98   5.00000 2021-01-25 17:32:32  2020-12-24 17:13:40   5.00000          0.00000             0.00000    15
99   4.50000 2021-01-25 15:09:45  2021-01-25 07:29:07  50.00000          0.00000             0.00000    15
100  5.00000 2021-01-25 10:39:05  2021-01-24 22:35:42   5.00000          0.00000             0.00000    15
101  5.00000 2021-01-24 18:47:59  2020-03-19 20:57:23   5.00000          0.00000             0.00000    16
102  5.00000 2021-01-24 15:14:33  2019-05-30 07:59:23  15.00000          0.00000             0.00000    16
103  4.50000 2021-01-24 14:03:11  2021-01-01 16:46:36   5.00000          0.00000             0.00000    16
104  5.00000 2021-01-24 12:46:01  2021-01-04 18:28:21  30.00000          0.00000             0.00000    16
105  4.00000 2021-01-24 12:28:11  2021-01-24 08:25:55  15.00000          0.00000             0.00000    16
106  5.00000 2021-01-24 10:51:47  2020-12-29 20:02:35  15.00000          0.00000             0.00000    16
107  5.00000 2021-01-24 08:43:13  2020-12-02 07:32:55  50.00000          0.00000             0.00000    16
108  4.50000 2021-01-23 22:44:03  2020-04-05 11:02:47  35.00000          0.00000             0.00000    17
109  4.50000 2021-01-23 19:24:26  2020-12-31 21:38:12   1.00000          0.00000             0.00000    17
110  5.00000 2021-01-23 18:57:28  2021-01-23 12:43:47  25.00000          0.00000             0.00000    17
111  5.00000 2021-01-23 17:46:26  2021-01-14 19:11:17  20.00000          0.00000             0.00000    17
112  5.00000 2021-01-22 19:11:38  2020-12-04 17:17:47  80.00000          1.00000             2.00000    18
113  4.00000 2021-01-22 09:08:13  2021-01-21 09:33:33   5.00000          0.00000             0.00000    18
114  5.00000 2021-01-22 08:08:05  2021-01-19 07:14:58   5.00000          0.00000             0.00000    18
115  5.00000 2021-01-21 22:11:40  2020-01-09 19:10:29  10.00000          0.00000             0.00000    19
116  5.00000 2021-01-21 18:44:16  2021-01-20 09:42:12  25.00000          0.00000             0.00000    19
117  5.00000 2021-01-21 17:17:27  2020-05-01 15:14:45  30.00000          0.00000             0.00000    19
118  4.50000 2021-01-21 15:22:42  2021-01-21 08:55:44   1.00000          0.00000             0.00000    19
119  5.00000 2021-01-21 11:49:21  2021-01-20 05:30:17   5.00000          0.00000             0.00000    19
120  5.00000 2021-01-21 09:27:41  2021-01-03 20:18:04   5.00000          0.00000             0.00000    19
121  5.00000 2021-01-21 08:46:45  2021-01-20 15:22:05  15.00000          0.00000             0.00000    19
122  5.00000 2021-01-21 05:41:13  2021-01-20 12:51:01  65.00000          0.00000             0.00000    19
123  5.00000 2021-01-20 20:00:20  2021-01-06 18:57:09  15.00000          0.00000             0.00000    20
124  4.50000 2021-01-20 19:50:41  2020-11-21 14:15:10  10.00000          0.00000             0.00000    20
125  5.00000 2021-01-20 18:37:29  2021-01-20 01:30:36  20.00000          0.00000             0.00000    20
126  5.00000 2021-01-20 17:12:19  2019-06-04 11:16:37   0.00000          0.00000             0.00000    20
127  5.00000 2021-01-19 22:56:44  2020-09-14 17:31:02  30.00000          0.00000             0.00000    21
128  5.00000 2021-01-19 16:50:09  2020-12-03 06:38:25  15.00000          0.00000             0.00000    21
129  5.00000 2021-01-19 14:27:28  2020-12-15 13:47:25  20.00000          0.00000             0.00000    21
130  5.00000 2021-01-19 11:03:03  2021-01-19 10:39:32   1.00000          0.00000             0.00000    21
131  5.00000 2021-01-19 10:14:39  2021-01-14 11:26:58  10.00000          0.00000             0.00000    21
132  3.50000 2021-01-19 01:29:01  2021-01-08 12:41:54  10.00000          0.00000             0.00000    21
133  5.00000 2021-01-18 23:19:50  2020-04-05 09:22:46   1.00000          0.00000             0.00000    22
134  5.00000 2021-01-18 21:09:08  2021-01-17 20:11:03  10.00000          0.00000             0.00000    22
135  5.00000 2021-01-17 22:33:40  2019-11-13 12:05:03  10.00000          0.00000             0.00000    23
136  5.00000 2021-01-17 22:22:24  2020-12-26 13:25:30   1.00000          0.00000             0.00000    23
137  5.00000 2021-01-17 19:45:29  2021-01-08 12:29:06  20.00000          0.00000             0.00000    23
138  5.00000 2021-01-17 19:09:36  2021-01-15 08:00:12  60.00000          0.00000             0.00000    23
139  5.00000 2021-01-17 18:39:44  2021-01-02 17:04:13  30.00000          0.00000             0.00000    23
140  5.00000 2021-01-17 17:35:20  2021-01-15 10:03:31  35.00000          0.00000             0.00000    23
141  4.50000 2021-01-17 14:35:23  2021-01-05 19:25:51  10.00000          0.00000             0.00000    23
142  5.00000 2021-01-17 14:24:30  2021-01-05 20:51:18  15.00000          1.00000             0.00000    23
143  5.00000 2021-01-17 12:24:18  2021-01-17 06:54:32  45.00000          0.00000             0.00000    23
144  4.50000 2021-01-17 11:13:09  2021-01-13 18:17:40   5.00000          0.00000             0.00000    23
145  5.00000 2021-01-17 10:52:33  2021-01-16 11:51:13   5.00000          0.00000             0.00000    23
146  5.00000 2021-01-17 03:29:40  2020-11-25 23:25:34  30.00000          0.00000             0.00000    23
147  5.00000 2021-01-17 00:04:38  2020-12-26 17:57:07   1.00000          0.00000             0.00000    23
148  5.00000 2021-01-16 22:22:44  2021-01-08 20:58:17   1.00000          0.00000             0.00000    24
149  5.00000 2021-01-16 22:16:16  2020-12-26 13:25:21  20.00000          0.00000             0.00000    24
150  5.00000 2021-01-16 17:43:14  2020-01-09 08:29:43  35.00000          0.00000             0.00000    24
151  5.00000 2021-01-16 16:57:18  2021-01-15 19:43:44  10.00000          0.00000             0.00000    24
152  5.00000 2021-01-16 16:49:29  2021-01-16 16:08:01  10.00000          2.00000             0.00000    24
153  5.00000 2021-01-16 14:54:39  2020-11-29 19:47:39  15.00000          0.00000             0.00000    24
154  4.00000 2021-01-16 13:54:39  2021-01-16 13:43:15  30.00000          0.00000             0.00000    24
155  4.00000 2021-01-16 13:36:37  2021-01-16 11:13:02   5.00000          0.00000             0.00000    24
156  5.00000 2021-01-16 13:02:42  2021-01-13 06:03:42   5.00000          0.00000             0.00000    24
157  5.00000 2021-01-16 12:33:22  2021-01-12 09:50:58  15.00000          0.00000             0.00000    24
158  4.50000 2021-01-16 11:17:22  2020-12-03 16:58:41   1.00000          0.00000             0.00000    24
159  5.00000 2021-01-16 08:44:28  2019-11-23 18:30:38  35.00000          0.00000             1.00000    24
160  4.50000 2021-01-15 22:51:07  2020-10-06 20:33:46  10.00000          0.00000             0.00000    25
161  5.00000 2021-01-15 20:34:11  2021-01-08 10:40:17  20.00000          0.00000             0.00000    25
162  5.00000 2021-01-15 18:47:51  2021-01-06 21:16:57   5.00000          0.00000             0.00000    25
163  5.00000 2021-01-15 18:05:05  2021-01-15 14:56:01   1.00000          0.00000             0.00000    25
164  5.00000 2021-01-15 15:19:00  2020-12-18 18:38:20  10.00000          0.00000             0.00000    25
165  5.00000 2021-01-14 21:26:27  2021-01-12 09:08:10  10.00000          0.00000             0.00000    26
166  5.00000 2021-01-14 14:03:14  2020-12-22 11:43:45  30.00000          0.00000             0.00000    26
167  4.50000 2021-01-13 21:49:32  2019-11-27 14:10:04 100.00000          2.00000             1.00000    27
168  4.00000 2021-01-13 12:16:51  2021-01-12 08:58:53  20.00000          0.00000             0.00000    27
169  5.00000 2021-01-13 09:15:07  2020-08-28 11:12:39   0.00000          0.00000             0.00000    27
170  5.00000 2021-01-13 06:49:33  2021-01-13 06:26:26  20.00000          0.00000             0.00000    27
171  5.00000 2021-01-13 00:22:06  2019-05-30 22:33:09   1.00000          0.00000             0.00000    27
172  5.00000 2021-01-12 19:25:14  2021-01-12 19:09:54  10.00000          0.00000             0.00000    28
173  3.00000 2021-01-12 11:21:08  2020-10-22 09:34:15   1.00000          0.00000             0.00000    28
174  5.00000 2021-01-12 09:51:38  2020-11-23 18:10:54 100.00000          0.00000             0.00000    28
175  5.00000 2021-01-12 05:29:55  2020-09-16 17:43:06  20.00000          0.00000             0.00000    28
176  4.00000 2021-01-12 04:01:50  2020-09-26 13:20:49  25.00000          0.00000             0.00000    28
177  5.00000 2021-01-11 22:49:08  2021-01-11 22:25:12   1.00000          0.00000             0.00000    29
178  5.00000 2021-01-11 22:17:47  2020-08-17 16:31:53   1.00000          0.00000             0.00000    29
179  4.50000 2021-01-11 20:42:42  2021-01-10 12:10:42  10.00000          0.00000             0.00000    29
180  4.50000 2021-01-11 20:31:28  2021-01-09 15:26:27   5.00000          0.00000             0.00000    29
181  5.00000 2021-01-11 20:02:33  2021-01-05 10:40:38   1.00000          0.00000             0.00000    29
182  5.00000 2021-01-11 17:04:13  2020-12-06 10:26:46 100.00000          0.00000             0.00000    29
183  5.00000 2021-01-11 14:06:01  2021-01-11 05:14:47   1.00000          0.00000             0.00000    29
184  4.50000 2021-01-11 13:18:31  2021-01-05 11:32:42  30.00000          1.00000             0.00000    29

In [62]:
# rating dagılımı
df["Rating"].value_counts() #Puanların dağılım bilgisine erişmek için

5.00000    3267
4.50000     475
4.00000     383
3.50000      96
3.00000      62
1.00000      15
2.00000      12
2.50000      11
1.50000       2
Name: Rating, dtype: int64

In [94]:
# Summary statistics
summary_stats = df.describe()
print("\nSummary Statistics:\n", summary_stats)

Summary Statistics:
           Rating   Progress  Questions Asked  Questions Answered       days
count 4323.00000 4323.00000       4323.00000          4323.00000 4323.00000
mean     4.76428   27.19755          0.22184             0.33102  291.15961
std      0.51959   29.14214          0.98956             6.21055  177.20125
min      1.00000    0.00000          0.00000             0.00000    4.00000
25%      5.00000    5.00000          0.00000             0.00000  140.00000
50%      5.00000   15.00000          0.00000             0.00000  286.00000
75%      5.00000   40.00000          0.00000             0.00000  411.00000
max      5.00000  100.00000         22.00000           356.00000  635.00000

In [63]:
df["Questions Asked"].value_counts() #sorulan sorular ilgili bir bilgi alalım

0.00000     3867
1.00000      276
2.00000       80
3.00000       43
4.00000       15
5.00000       13
6.00000        9
8.00000        5
9.00000        3
14.00000       2
11.00000       2
7.00000        2
10.00000       2
15.00000       2
22.00000       1
12.00000       1
Name: Questions Asked, dtype: int64

In [95]:
# Average Rating
average_rating = df['Rating'].mean()
print("\nAverage Rating:", average_rating)

Average Rating: 4.764284061993986

In [64]:
df.groupby("Questions Asked").agg({"Questions Asked": "count",
                                   "Rating": "mean"})

                 Questions Asked  Rating
Questions Asked
0.00000                     3867 4.76519
1.00000                      276 4.74094
2.00000                       80 4.80625
3.00000                       43 4.74419
4.00000                       15 4.83333
5.00000                       13 4.65385
6.00000                        9 5.00000
7.00000                        2 4.75000
8.00000                        5 4.90000
9.00000                        3 5.00000
10.00000                       2 5.00000
11.00000                       2 5.00000
12.00000                       1 5.00000
14.00000                       2 4.50000
15.00000                       2 3.00000
22.00000                       1 5.00000

In [96]:
# Latest Timestamp
latest_timestamp = df['Timestamp'].max()
print("\nLatest Timestamp:", latest_timestamp)

Latest Timestamp: 2021-02-05 07:45:55

In [65]:
df.head()
#asıl amacımız: bu kursa verilen puanların puanını hesaplamak

   Rating            Timestamp             Enrolled  Progress  Questions Asked  Questions Answered
0 5.00000  2021-02-05 07:45:55  2021-01-25 15:12:08   5.00000          0.00000             0.00000
1 5.00000  2021-02-04 21:05:32  2021-02-04 20:43:40   1.00000          0.00000             0.00000
2 4.50000  2021-02-04 20:34:03  2019-07-04 23:23:27   1.00000          0.00000             0.00000
3 5.00000  2021-02-04 16:56:28  2021-02-04 14:41:29  10.00000          0.00000             0.00000
4 4.00000  2021-02-04 15:00:24  2020-10-13 03:10:07  10.00000          0.00000             0.00000

In [97]:
# Total Enrolled
total_enrolled = df['Enrolled'].sum()
print("\nTotal Enrolled:", total_enrolled)

Total Enrolled: 2021-01-25 15:12:082021-02-04 20:43:402019-07-04 23:23:272021-02-04 14:41:292020-10-13 03:10:072021-02-01 15:40:132020-11-30 19:23:542021-01-08 08:05:422021-02-02 18:14:492020-08-01 22:30:422021-02-01 09:54:492021-02-01 18:45:002021-02-03 20:00:042021-02-03 18:42:212020-03-29 09:07:412020-03-19 19:28:432021-02-01 09:23:312021-01-28 20:46:122019-07-25 08:04:262021-02-02 07:15:552021-02-02 17:47:412021-01-19 22:29:492021-01-03 19:42:392021-01-27 13:11:182021-02-02 16:10:522020-04-04 22:14:152021-02-02 09:07:032020-09-20 12:26:302021-02-02 10:07:222020-08-20 19:14:012021-01-31 14:58:492021-01-24 17:58:232021-02-01 12:08:222021-02-01 11:14:172021-02-01 06:15:182021-01-29 08:29:312020-11-22 16:09:362021-01-30 10:23:032021-01-31 21:29:472019-11-18 11:37:062020-12-21 16:29:262021-01-07 23:14:522021-01-13 09:37:262021-01-25 10:17:432021-01-06 10:56:432021-01-30 12:58:112019-09-26 09:11:422021-01-31 11:01:522021-01-18 20:24:402020-04-05 03:00:252020-06-19 09:33:062020-12-20 14:12:512020-12-02 13:50:482021-01-30 15:57:152020-12-11 18:14:022021-01-25 21:45:332020-12-19 14:24:202021-01-30 13:29:102021-01-29 15:04:392021-01-08 13:01:122020-10-01 22:02:512021-01-28 11:56:462021-01-27 17:39:072021-01-25 11:14:112021-01-25 12:44:462021-01-29 15:07:152020-10-21 14:07:392021-01-24 19:57:272021-01-29 14:50:132021-01-25 12:33:502020-11-18 12:17:202021-01-29 07:34:412021-01-29 10:48:002020-12-24 09:02:222020-12-11 15:27:552020-08-21 05:03:492020-12-16 16:24:542021-01-27 08:43:492020-12-01 15:11:042021-01-25 12:45:432021-01-01 16:29:472021-01-22 13:20:492021-01-27 20:29:572020-12-21 14:59:052021-01-21 18:29:242021-01-19 16:25:492020-02-27 18:19:162021-01-20 15:02:502021-01-05 08:30:512021-01-26 14:48:572019-11-16 07:51:592020-12-01 19:33:382020-12-29 07:29:582020-01-08 12:52:262020-11-05 11:06:132021-01-01 11:27:342020-11-30 19:35:462020-03-23 16:51:552020-12-24 17:13:402021-01-25 07:29:072021-01-24 22:35:422020-03-19 20:57:232019-05-30 07:59:232021-01-01 16:46:362021-01-04 18:28:212021-01-24 08:25:552020-12-29 20:02:352020-12-02 07:32:552020-04-05 11:02:472020-12-31 21:38:122021-01-23 12:43:472021-01-14 19:11:172020-12-04 17:17:472021-01-21 09:33:332021-01-19 07:14:582020-01-09 19:10:292021-01-20 09:42:122020-05-01 15:14:452021-01-21 08:55:442021-01-20 05:30:172021-01-03 20:18:042021-01-20 15:22:052021-01-20 12:51:012021-01-06 18:57:092020-11-21 14:15:102021-01-20 01:30:362019-06-04 11:16:372020-09-14 17:31:022020-12-03 06:38:252020-12-15 13:47:252021-01-19 10:39:322021-01-14 11:26:582021-01-08 12:41:542020-04-05 09:22:462021-01-17 20:11:032019-11-13 12:05:032020-12-26 13:25:302021-01-08 12:29:062021-01-15 08:00:122021-01-02 17:04:132021-01-15 10:03:312021-01-05 19:25:512021-01-05 20:51:182021-01-17 06:54:322021-01-13 18:17:402021-01-16 11:51:132020-11-25 23:25:342020-12-26 17:57:072021-01-08 20:58:172020-12-26 13:25:212020-01-09 08:29:432021-01-15 19:43:442021-01-16 16:08:012020-11-29 19:47:392021-01-16 13:43:152021-01-16 11:13:022021-01-13 06:03:422021-01-12 09:50:582020-12-03 16:58:412019-11-23 18:30:382020-10-06 20:33:462021-01-08 10:40:172021-01-06 21:16:572021-01-15 14:56:012020-12-18 18:38:202021-01-12 09:08:102020-12-22 11:43:452019-11-27 14:10:042021-01-12 08:58:532020-08-28 11:12:392021-01-13 06:26:262019-05-30 22:33:092021-01-12 19:09:542020-10-22 09:34:152020-11-23 18:10:542020-09-16 17:43:062020-09-26 13:20:492021-01-11 22:25:122020-08-17 16:31:532021-01-10 12:10:422021-01-09 15:26:272021-01-05 10:40:382020-12-06 10:26:462021-01-11 05:14:472021-01-05 11:32:422020-12-21 22:06:122020-11-08 07:51:372021-01-11 06:15:552020-12-30 17:14:572021-01-06 09:44:342020-06-30 20:14:042020-12-31 20:33:132020-03-03 08:29:432020-12-04 20:01:012019-10-24 14:50:492021-01-09 19:18:272019-12-10 17:30:242019-10-28 20:14:132020-12-17 10:22:592020-12-19 11:23:472020-12-30 20:37:092021-01-08 07:29:472021-01-09 08:57:142020-11-27 12:40:542021-01-09 12:09:302020-10-06 05:53:332021-01-09 11:02:002020-12-05 11:19:122021-01-08 13:45:062021-01-03 12:14:302020-12-29 20:06:402021-01-08 15:27:172021-01-03 20:04:252021-01-07 18:54:512021-01-01 16:55:222020-12-30 16:32:212021-01-07 20:52:432020-11-06 14:19:332021-01-07 09:40:022020-12-23 12:50:282020-10-30 09:54:222021-01-06 14:29:362020-12-15 16:53:012021-01-06 16:56:532020-12-01 15:13:502020-03-15 16:00:532021-01-02 19:32:242021-01-06 11:56:282020-04-04 22:48:392021-01-06 06:07:372021-01-04 10:22:542021-01-05 13:22:292021-01-05 13:20:532021-01-04 14:03:042021-01-03 20:12:332020-12-24 07:32:302020-07-26 19:01:392020-12-24 19:15:332020-10-15 18:22:592021-01-04 19:24:392021-01-04 17:49:292021-01-04 16:28:562021-01-04 10:08:382020-04-24 09:20:302021-01-02 13:25:002021-01-03 12:45:342020-11-28 07:50:542020-08-02 11:12:342020-04-18 13:23:072020-05-18 23:12:212020-11-28 23:29:212020-11-03 08:34:122021-01-02 16:30:442019-12-25 21:07:372020-12-21 05:32:112020-07-15 17:01:322021-01-01 18:42:522020-09-10 13:23:102021-01-02 11:40:152021-01-02 18:06:152021-01-02 09:48:132020-12-01 17:17:172020-12-31 13:03:422021-01-02 17:53:452021-01-02 18:51:002020-12-29 08:11:022021-01-02 09:16:072020-10-25 19:19:552020-11-30 18:22:372021-01-01 13:03:162021-01-02 10:22:012019-11-29 07:55:242021-01-01 19:30:292020-11-30 23:48:132020-11-08 09:41:492021-01-01 15:26:172020-12-15 16:19:242021-01-01 13:02:332020-12-30 10:47:472020-11-29 12:05:242020-12-31 18:13:002021-01-01 09:58:052020-12-30 13:53:442021-01-01 09:16:002020-12-31 11:41:442020-12-31 06:18:362020-12-15 22:11:432020-12-31 06:10:082020-04-05 14:13:182020-05-07 12:26:142020-12-29 21:44:482020-04-05 13:42:272020-10-15 16:58:292020-10-14 14:23:162020-12-27 12:40:122020-12-29 06:34:282020-12-25 12:23:532020-04-05 10:23:232020-12-21 05:45:002020-12-28 20:20:022020-12-11 13:58:062020-04-05 10:45:352020-12-11 11:57:192020-12-28 09:24:262020-04-05 00:20:042020-12-10 09:59:542020-12-27 17:08:332020-06-19 14:21:292020-12-27 15:28:032020-12-27 13:14:392020-12-27 12:52:082020-12-26 19:09:532020-12-26 13:48:232020-12-26 18:52:062019-07-02 20:25:132020-12-26 13:19:452020-04-05 10:54:512020-12-26 15:21:102020-10-17 21:39:512020-11-09 20:18:212020-12-25 21:40:542020-12-26 13:55:452019-05-15 18:25:372019-06-14 03:40:022020-12-12 21:00:152020-10-08 00:03:442020-11-10 11:25:382020-12-24 11:51:162020-09-06 08:30:352020-12-25 17:27:172020-12-17 15:51:292020-12-23 13:10:082020-12-25 14:17:482020-12-24 20:34:032020-11-04 12:20:142020-12-22 20:07:532020-11-21 18:38:422020-05-06 22:23:522019-07-25 20:37:252020-12-23 13:00:232020-12-24 13:26:282020-05-19 11:07:062020-10-05 06:17:062019-11-19 10:47:362020-12-07 04:56:452020-03-04 06:17:522020-12-10 11:46:162020-12-01 14:17:022020-12-23 18:52:362020-12-16 14:12:242020-12-23 05:29:382019-05-21 12:03:482020-12-22 06:01:512020-04-05 12:35:562020-10-09 15:30:562020-12-21 14:29:372020-12-20 21:39:492020-12-21 21:42:332020-12-21 19:36:022020-12-09 14:19:112020-12-02 11:46:242020-12-21 19:32:312020-11-22 20:57:012020-06-04 07:26:132020-12-21 18:50:382020-04-21 08:44:242020-12-21 16:36:582020-11-29 15:26:352020-10-03 17:49:292020-12-20 17:57:022019-05-23 18:38:182020-12-20 21:08:232020-12-17 11:30:452020-11-06 04:27:532019-11-15 06:36:582020-08-08 09:39:552020-12-20 08:06:142020-12-19 20:20:052020-06-20 11:53:022020-12-19 21:34:152020-05-03 18:03:122020-11-27 14:15:562020-11-08 19:19:262020-12-19 16:19:062020-12-17 15:45:592020-11-30 23:35:402020-12-17 09:39:552020-12-08 18:23:202020-12-19 10:44:272020-12-19 11:01:372020-12-18 09:18:562020-12-18 20:41:562020-12-16 20:28:232020-12-09 02:05:462020-12-16 21:51:322020-09-17 12:29:052020-11-06 20:26:342020-10-19 19:14:152020-11-21 21:37:462020-12-17 18:38:192020-11-29 08:21:252020-12-11 18:15:282020-12-17 15:54:372020-08-26 16:07:082020-10-28 07:30:422020-12-17 13:18:292020-11-26 08:52:252020-11-30 19:59:252020-12-15 17:27:212020-04-11 20:22:542020-12-02 22:19:212020-12-15 14:53:102020-12-14 22:10:542020-11-28 14:36:462020-11-09 10:23:182020-12-04 13:05:082020-12-15 08:53:232020-12-14 12:44:202020-11-20 01:09:482019-06-12 17:10:372020-12-15 20:10:372020-12-15 15:08:172020-12-15 11:46:422020-11-29 11:26:062020-12-15 08:26:062019-06-05 01:01:472020-12-15 06:27:372020-12-13 21:15:452020-12-13 11:08:222020-11-29 11:45:572020-12-11 08:51:142020-12-09 10:47:422020-02-01 14:30:422020-02-03 14:04:022020-11-22 15:49:152020-04-05 13:27:162020-10-15 11:35:242020-12-02 18:50:152020-11-28 05:33:342020-09-28 17:40:142020-07-12 11:42:412020-11-30 13:48:552020-09-16 21:47:532020-08-31 22:04:282020-12-08 16:59:122020-12-10 06:50:272019-07-26 17:53:002020-04-02 06:33:252020-07-16 03:09:442019-08-28 09:18:222020-01-01 15:47:452020-12-10 19:16:542020-10-13 13:11:002020-08-24 07:56:222020-12-11 17:24:142020-12-04 18:36:282020-12-01 17:16:462020-12-10 18:13:142020-12-06 17:30:022020-10-05 13:57:072020-11-23 21:22:432020-12-02 11:42:192020-12-07 21:19:182020-12-03 18:08:102020-12-10 10:00:362020-10-26 19:36:002020-12-01 17:19:552020-12-10 11:33:502020-11-27 20:25:282020-07-23 03:34:542020-11-26 08:06:282019-07-31 00:10:252020-12-04 16:15:042020-10-05 13:44:262020-12-01 07:19:502020-11-30 19:08:182020-12-07 15:01:142020-12-07 15:30:342020-12-03 09:33:022020-12-05 10:33:112020-12-07 20:18:432020-12-07 13:01:542020-07-18 18:23:532020-08-26 17:41:112020-09-13 13:39:112019-10-05 13:02:172020-11-15 17:35:482020-12-06 17:56:092019-05-25 10:10:372020-11-19 10:27:082020-12-04 23:38:262020-11-29 10:21:182020-12-01 06:16:292020-08-22 18:40:272020-04-13 09:49:572020-12-02 12:14:582020-12-06 01:22:102020-11-10 21:27:382020-12-04 18:27:162020-12-04 18:50:312020-11-30 09:22:142020-11-30 20:11:572020-11-23 12:17:022020-01-25 18:45:462020-11-27 17:01:012020-09-17 20:41:422020-12-01 17:33:252020-12-03 18:17:322020-11-22 10:48:012020-06-02 10:16:412020-12-04 17:58:272020-12-05 11:20:202020-11-24 14:53:012020-11-24 21:29:012020-12-03 15:50:112019-11-23 13:53:192019-12-04 19:01:072020-12-03 22:01:372020-11-29 08:54:082020-06-30 08:46:262020-12-04 08:44:502020-12-04 00:05:452019-05-21 14:16:362020-04-04 22:49:532020-12-03 13:41:112020-10-21 14:49:332020-01-06 11:11:542020-03-28 14:41:202020-12-02 18:58:382020-12-03 15:07:172020-11-28 14:44:342020-11-29 12:21:182020-10-22 20:36:212020-12-03 10:44:462020-12-03 10:03:412020-04-01 12:17:472020-04-02 14:52:522020-12-02 12:34:442020-11-27 13:12:552020-11-22 14:43:132020-08-12 13:44:272019-06-11 01:50:382020-12-01 09:36:542020-11-04 14:07:452020-12-01 17:26:422020-11-30 18:52:532019-07-31 16:08:502020-11-29 13:33:002020-04-02 10:08:452020-11-06 19:43:202020-11-30 22:38:292020-12-01 09:57:552020-04-03 14:45:212020-11-30 22:18:162020-11-28 14:11:052020-11-22 06:38:272020-10-31 20:24:342019-11-28 16:21:062020-04-03 19:43:202020-11-30 13:32:592020-04-05 07:41:442019-12-25 11:03:512020-11-11 11:30:222020-11-20 17:30:202020-11-29 20:58:252020-11-26 20:06:182020-11-29 17:55:202020-11-23 14:46:272020-07-22 20:08:572020-11-29 11:18:512020-11-20 09:37:322020-11-04 17:40:232020-11-21 05:02:312020-11-26 19:34:522020-11-02 11:52:032020-11-27 20:46:082020-04-02 13:09:232020-11-25 13:45:522020-04-17 18:53:522020-05-11 15:52:282020-11-11 13:19:072020-11-16 19:17:092020-11-27 14:18:372020-11-27 20:29:022020-11-27 18:39:542020-11-27 17:31:212020-11-26 16:24:022020-11-19 21:24:182020-11-24 19:59:172020-11-26 06:54:282019-10-24 14:47:142020-05-10 03:31:102020-06-02 12:09:272020-11-24 19:00:412019-07-30 10:49:482020-11-26 09:06:112020-11-25 19:25:482020-11-24 14:14:082020-10-03 10:16:072020-11-25 22:02:112020-10-06 10:38:552020-11-05 07:43:012020-11-24 09:29:412020-11-18 10:29:402020-11-25 15:44:402020-08-21 15:19:022020-10-12 11:55:052020-11-24 15:09:522020-11-22 07:30:532020-02-05 07:21:082020-08-12 22:05:342020-11-24 11:26:432019-12-25 21:02:392020-11-23 20:00:282020-11-23 19:19:322020-11-14 19:17:252020-11-20 09:04:172020-04-04 23:12:322020-11-23 13:07:382020-06-28 07:35:572020-11-23 11:16:502020-05-11 05:53:342020-11-23 11:11:222020-11-22 19:13:182020-11-23 08:32:482020-11-22 19:06:522020-11-22 17:46:472020-10-28 20:00:332020-11-11 08:41:322020-11-21 10:10:142020-11-21 17:41:292020-11-22 07:22:592020-11-20 12:45:452020-08-05 07:47:342020-11-22 08:04:582020-11-21 21:29:262020-10-25 14:13:452020-08-14 11:21:212019-07-25 19:28:532020-11-20 13:15:232020-11-20 18:20:322020-11-21 15:15:572020-11-21 07:16:092020-04-05 13:03:432020-03-08 21:09:552020-11-10 22:06:372020-11-20 13:51:502020-11-20 08:14:512020-11-04 22:54:172019-07-17 08:09:192020-11-12 08:29:202020-11-17 06:29:392020-11-11 05:19:432020-11-17 23:25:382020-11-17 20:40:252019-11-29 20:46:502020-05-18 14:48:312020-11-11 21:21:062020-11-17 16:31:072020-11-14 20:27:052020-01-21 11:21:112020-11-17 13:01:502020-11-17 11:41:572020-11-17 06:56:122020-08-15 10:36:032020-11-16 19:05:432020-11-15 19:14:172020-11-05 19:24:372019-10-14 21:49:172020-04-05 13:41:112019-11-04 16:14:172020-01-05 13:19:042020-09-23 15:20:242020-11-16 09:41:342020-11-09 14:48:142020-11-15 19:46:492020-11-14 15:17:562019-11-23 22:59:252020-09-25 16:15:502020-10-14 18:55:182019-07-16 14:56:442020-11-04 18:21:392020-11-12 11:24:522020-11-10 07:01:402019-09-30 12:31:212020-11-13 12:29:112020-11-02 12:51:212020-11-11 19:01:342020-11-13 11:55:412020-11-13 16:14:252020-11-13 11:49:462020-05-21 10:43:172020-11-05 06:21:172020-11-12 13:28:212020-03-16 09:32:052020-08-10 06:06:322020-05-09 08:01:192019-05-22 15:21:412019-05-20 12:32:402020-11-02 09:32:262020-10-15 19:35:182020-04-05 01:52:042020-10-30 08:05:242020-11-09 20:43:062020-11-06 09:19:322020-10-15 10:46:282020-11-08 22:39:262020-11-05 15:13:282020-11-09 05:22:182019-12-27 16:48:122019-08-29 14:41:202020-09-12 17:12:172020-01-29 10:09:232020-11-05 07:15:212020-11-05 13:49:522020-07-07 11:41:372020-04-02 15:43:532020-09-17 22:41:532019-06-14 18:10:392020-10-15 09:17:302020-11-01 19:40:182020-11-08 13:49:272020-11-07 19:41:572020-11-07 15:38:342019-05-20 13:49:562020-11-08 07:45:232020-10-18 17:30:262020-11-03 12:05:232020-11-07 18:15:122020-10-08 14:39:202020-11-06 09:45:092020-04-05 10:27:432020-07-27 10:01:482020-11-05 11:59:162020-11-06 11:37:212020-11-06 11:42:532020-11-04 13:56:412020-11-05 06:33:412020-11-05 20:30:242020-11-05 17:28:472020-10-23 11:14:592020-10-24 22:22:252020-10-23 17:28:552020-10-27 19:29:312020-11-04 19:14:512020-11-04 17:15:172020-11-04 13:08:202020-07-20 21:10:072020-07-27 10:57:492019-05-22 00:11:092020-11-03 18:48:452020-10-09 15:34:192020-11-03 17:36:152020-09-25 15:58:542020-10-24 15:02:032020-11-03 12:15:002020-10-24 09:39:552020-10-27 20:59:282020-10-26 18:27:312020-10-31 18:41:192020-11-02 21:37:212020-01-10 20:56:462020-10-28 18:33:172020-11-02 15:48:322020-11-01 12:16:532020-01-29 15:19:572020-05-06 22:47:502020-10-17 20:00:172020-10-24 18:29:542020-10-14 10:22:302019-09-29 17:19:232020-10-31 12:18:482020-10-30 13:25:372019-10-13 11:19:542019-11-19 16:34:542020-10-28 23:38:242020-08-13 12:38:402020-04-06 19:25:492020-08-28 11:13:512020-06-30 13:18:082020-10-09 21:10:482020-07-07 13:10:522020-10-29 12:16:362020-04-05 11:23:362020-10-29 09:51:422020-10-20 08:49:522020-09-08 10:36:202020-10-29 07:42:382020-10-17 13:50:322020-10-27 15:26:342020-10-28 21:22:582020-01-28 21:14:482020-10-27 19:31:002020-10-22 14:55:102020-10-21 18:23:332020-10-28 09:39:582020-10-24 19:22:182020-10-27 12:26:262019-11-27 07:09:172020-10-25 17:10:582020-04-05 09:32:262020-10-22 21:20:112020-10-26 15:49:262020-08-05 09:05:342020-02-05 07:27:362020-10-25 18:21:472020-10-25 16:53:252020-10-25 15:50:352020-03-27 11:36:162020-10-22 20:00:432020-10-24 14:57:202020-10-25 07:41:342020-04-10 10:00:142020-10-24 19:15:492020-10-23 19:46:292020-10-24 15:37:542020-08-05 17:29:002020-10-23 19:03:522019-07-28 23:13:482020-10-21 18:46:162020-10-21 12:36:552020-10-19 09:05:302020-04-07 22:07:282020-10-21 21:46:522020-04-05 00:34:152020-10-18 09:47:182020-08-09 12:51:362020-10-19 19:25:222020-10-14 17:27:482020-08-08 18:03:292019-08-28 20:33:092020-10-22 10:22:282020-10-20 11:56:262020-10-21 11:22:552020-10-06 19:59:292019-06-06 14:49:562020-10-20 16:53:262019-12-03 06:37:242019-06-13 12:01:122019-08-28 12:49:322020-10-21 14:12:512020-10-20 06:44:492020-10-19 11:47:212020-10-16 14:39:302020-10-15 11:26:582020-03-29 10:21:492020-06-18 02:44:042020-10-19 09:43:362020-10-19 14:18:132020-10-19 07:19:392020-09-17 11:26:362020-10-19 20:41:072020-09-16 17:15:492020-10-19 20:38:352020-10-09 10:35:182020-04-05 10:54:512020-10-19 08:15:202020-10-14 17:18:042020-10-17 17:17:492020-09-07 16:43:482020-10-18 07:09:402020-10-18 16:24:502020-10-15 18:50:102020-10-18 13:25:002020-10-18 13:51:542020-10-17 13:22:542020-05-07 11:41:162020-10-10 11:52:422020-06-03 14:10:102020-04-23 11:05:542020-10-16 12:34:272020-10-16 17:11:252020-10-11 17:33:452020-10-16 15:50:592020-10-16 12:47:582020-10-02 16:53:522020-10-14 20:03:342020-10-01 22:17:082020-10-13 19:04:452020-10-09 15:44:172020-10-14 13:44:542020-10-15 12:59:542020-08-08 17:00:392020-10-10 19:18:192020-10-14 23:18:552020-10-09 11:47:362020-10-12 18:36:152020-10-07 09:19:082019-12-06 23:00:332020-08-31 10:56:402020-04-05 09:39:082020-10-13 21:27:452020-08-28 10:07:382020-02-12 21:12:532020-10-07 11:55:112020-10-08 17:59:322020-04-05 12:17:552019-11-06 07:40:032020-08-29 18:26:402020-10-12 21:36:082020-10-09 16:29:132020-07-27 18:48:432020-10-02 08:25:572020-08-18 01:27:532020-04-05 11:02:482020-09-22 08:19:012020-10-09 12:26:442020-08-21 08:12:582020-10-12 12:05:552020-10-11 18:34:432020-09-21 13:21:562020-10-09 09:33:262020-09-07 18:36:442020-10-08 17:31:562020-10-11 21:20:472020-10-04 10:51:012020-02-03 10:35:492020-10-11 10:54:512020-10-11 10:35:322020-10-11 05:19:342020-10-09 19:27:432020-10-08 18:20:072020-10-09 17:42:232020-10-09 15:43:102020-09-28 17:01:402020-10-09 20:01:032020-10-01 14:50:552020-10-08 19:11:002020-08-27 09:05:392020-09-15 08:10:192020-09-20 09:44:002020-09-12 21:05:422020-10-08 17:38:272020-10-08 16:23:152020-10-02 06:57:512020-04-08 16:13:382020-10-06 19:33:292020-10-08 14:47:062020-09-14 14:37:442020-08-28 14:28:302020-07-03 13:39:472020-09-30 20:59:542020-09-18 17:44:072019-12-11 19:31:222020-10-07 17:18:572019-06-13 06:12:052020-10-06 14:44:182020-10-07 18:42:142020-10-07 11:59:292020-10-07 11:17:492020-09-30 11:06:082019-06-05 09:22:492020-10-01 12:57:342020-10-07 12:11:452020-10-06 12:06:152020-10-06 07:54:252020-08-27 15:58:132020-08-04 15:37:502020-08-27 14:58:392020-10-06 21:44:152020-04-05 16:03:042020-08-19 08:51:572020-01-05 12:57:302020-10-06 08:58:282020-10-05 12:19:322020-08-31 09:47:152020-04-05 10:58:102020-07-03 10:35:102020-10-05 16:18:282020-09-26 07:11:532020-10-02 11:41:442020-09-28 20:16:282019-10-03 07:27:432020-09-28 06:37:542020-09-28 21:24:272020-09-24 08:11:222020-04-05 11:37:462019-10-20 09:16:252020-08-17 18:10:122020-10-04 18:16:372020-08-09 11:49:132020-10-03 13:20:572020-08-29 20:05:532020-10-02 19:34:072020-09-23 16:07:552020-09-17 17:46:122020-09-27 23:34:202020-10-01 13:29:122020-10-02 17:34:172019-12-04 18:27:312020-10-02 16:46:552020-10-02 17:48:362020-10-02 14:41:012020-03-03 16:36:492019-12-05 12:27:422020-10-02 17:58:152019-06-16 18:42:122020-09-11 20:36:322020-06-29 03:25:142020-08-18 07:01:042020-09-24 22:12:432020-10-02 15:59:532020-06-30 06:17:252020-10-02 14:00:472020-08-18 08:00:412020-10-02 10:33:032020-10-01 10:07:332020-08-13 21:01:372020-09-29 18:35:182020-09-30 15:55:532020-10-01 12:38:202020-06-02 09:30:392020-10-01 10:09:112020-09-30 17:47:152020-10-01 08:50:022020-10-01 08:07:332020-09-30 05:26:082020-09-16 21:48:232020-09-30 19:37:392020-09-28 18:59:522020-05-28 08:21:092020-04-05 11:48:212020-09-30 13:28:462020-09-30 12:53:102020-09-30 10:24:412020-09-22 10:17:102020-09-25 13:46:452020-09-22 06:21:522020-04-12 10:58:392020-09-23 13:43:372020-09-10 18:40:122020-09-29 11:09:092020-09-10 13:32:412020-09-26 21:26:512020-09-29 00:21:172020-09-15 12:36:022020-08-05 09:05:202020-03-08 14:04:522020-09-11 16:10:512020-04-16 13:23:042020-09-11 14:39:472020-09-28 13:02:192020-09-27 15:57:582020-09-21 11:29:042020-01-30 13:53:112020-02-05 20:06:102020-09-26 18:44:042020-09-20 12:04:542020-09-21 07:23:332020-09-26 20:33:302020-09-05 19:26:552020-09-26 18:2

In [66]:
####################
# Average
####################

In [98]:
# Average Progress
average_progress = df['Progress'].mean()
print("\nAverage Progress:", average_progress)

Average Progress: 27.197547999074718

In [99]:
# Total Questions Asked and Answered
total_questions_asked = df['Questions Asked'].sum()
total_questions_answered = df['Questions Answered'].sum()
print("\nTotal Questions Asked:", total_questions_asked)
print("Total Questions Answered:", total_questions_answered)

Total Questions Asked: 959.0
Total Questions Answered: 1431.0

In [100]:
# Correlation between columns
correlation_matrix = df.corr()
print("\nCorrelation Matrix:\n", correlation_matrix)

Correlation Matrix:
                      Rating  Progress  Questions Asked  Questions Answered     days
Rating              1.00000   0.10202         -0.01055             0.00884  0.00418
Progress            0.10202   1.00000          0.22119             0.08859 -0.07180
Questions Asked    -0.01055   0.22119          1.00000             0.14493  0.05663
Questions Answered  0.00884   0.08859          0.14493             1.00000  0.01927
days                0.00418  -0.07180          0.05663             0.01927  1.00000

In [67]:
# Ortalama Puan
df["Rating"].mean()

4.764284061993986

In [68]:
####################
# Time-Based Weighted Average
####################
# Puan Zamanlarına Göre Ağırlıklı Ortalama

In [69]:
df.head()

   Rating            Timestamp             Enrolled  Progress  Questions Asked  Questions Answered
0 5.00000  2021-02-05 07:45:55  2021-01-25 15:12:08   5.00000          0.00000             0.00000
1 5.00000  2021-02-04 21:05:32  2021-02-04 20:43:40   1.00000          0.00000             0.00000
2 4.50000  2021-02-04 20:34:03  2019-07-04 23:23:27   1.00000          0.00000             0.00000
3 5.00000  2021-02-04 16:56:28  2021-02-04 14:41:29  10.00000          0.00000             0.00000
4 4.00000  2021-02-04 15:00:24  2020-10-13 03:10:07  10.00000          0.00000             0.00000

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4323 entries, 0 to 4322
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rating              4323 non-null   float64
 1   Timestamp           4323 non-null   object
 2   Enrolled            4323 non-null   object
 3   Progress            4323 non-null   float64
 4   Questions Asked     4323 non-null   float64
 5   Questions Answered  4323 non-null   float64
dtypes: float64(4), object(2)
memory usage: 202.8+ KB

In [103]:
# "Timestamp" sütununu datetime türüne dönüştür
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

# Değişiklikleri doğrulamak için DataFrame'i görüntüleyin
print(" 'Timestamp' sütununu datetime türüne dönüştürdükten sonra DataFrame:")
print(df)

 'Timestamp' sütununu datetime türüne dönüştürdükten sonra DataFrame:
      Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  days
0    5.00000 2021-02-05 07:45:55  2021-01-25 15:12:08   5.00000          0.00000             0.00000     4
1    5.00000 2021-02-04 21:05:32  2021-02-04 20:43:40   1.00000          0.00000             0.00000     5
2    4.50000 2021-02-04 20:34:03  2019-07-04 23:23:27   1.00000          0.00000             0.00000     5
3    5.00000 2021-02-04 16:56:28  2021-02-04 14:41:29  10.00000          0.00000             0.00000     5
4    4.00000 2021-02-04 15:00:24  2020-10-13 03:10:07  10.00000          0.00000             0.00000     5
5    4.00000 2021-02-04 12:42:36  2021-02-01 15:40:13   1.00000          0.00000             0.00000     5
6    5.00000 2021-02-04 12:25:30  2020-11-30 19:23:54  85.00000          0.00000             4.00000     5
7    4.50000 2021-02-04 11:13:15  2021-01-08 08:05:42  10.00000          0.00000             0.00000     5
8    5.00000 2021-02-04 08:59:53  2021-02-02 18:14:49   1.00000          0.00000             0.00000     5
9    5.00000 2021-02-03 22:40:04  2020-08-01 22:30:42  35.00000          0.00000             0.00000     6
10   5.00000 2021-02-03 21:26:02  2021-02-01 09:54:49   5.00000          0.00000             0.00000     6
11   5.00000 2021-02-03 21:14:25  2021-02-01 18:45:00   1.00000          0.00000             0.00000     6
12   5.00000 2021-02-03 20:55:19  2021-02-03 20:00:04  10.00000          0.00000             0.00000     6
13   3.00000 2021-02-03 19:16:45  2021-02-03 18:42:21   1.00000          0.00000             0.00000     6
14   5.00000 2021-02-03 19:08:33  2020-03-29 09:07:41  93.00000          1.00000             0.00000     6
15   5.00000 2021-02-03 18:57:11  2020-03-19 19:28:43   1.00000          0.00000             0.00000     6
16   2.50000 2021-02-03 18:56:58  2021-02-01 09:23:31   5.00000          0.00000             0.00000     6
17   5.00000 2021-02-03 17:21:45  2021-01-28 20:46:12   5.00000          0.00000             0.00000     6
18   5.00000 2021-02-03 17:12:26  2019-07-25 08:04:26  35.00000          0.00000             0.00000     6
19   5.00000 2021-02-03 16:13:36  2021-02-02 07:15:55   5.00000          0.00000             0.00000     6
20   4.00000 2021-02-02 23:55:23  2021-02-02 17:47:41   1.00000          0.00000             0.00000     7
21   5.00000 2021-02-02 22:34:25  2021-01-19 22:29:49   5.00000          0.00000             0.00000     7
22   5.00000 2021-02-02 21:59:49  2021-01-03 19:42:39  35.00000          0.00000             0.00000     7
23   5.00000 2021-02-02 18:00:59  2021-01-27 13:11:18   1.00000          0.00000             0.00000     7
24   5.00000 2021-02-02 16:29:58  2021-02-02 16:10:52  15.00000          0.00000             0.00000     7
25   5.00000 2021-02-02 14:30:03  2020-04-04 22:14:15  25.00000          0.00000             0.00000     7
26   5.00000 2021-02-02 12:54:25  2021-02-02 09:07:03  15.00000          0.00000             0.00000     7
27   5.00000 2021-02-02 12:02:59  2020-09-20 12:26:30   1.00000          0.00000             0.00000     7
28   5.00000 2021-02-02 11:58:42  2021-02-02 10:07:22  20.00000          0.00000             0.00000     7
29   5.00000 2021-02-02 10:47:54  2020-08-20 19:14:01   5.00000          0.00000             0.00000     7
30   5.00000 2021-02-02 04:58:56  2021-01-31 14:58:49  15.00000          0.00000             0.00000     7
31   5.00000 2021-02-01 21:27:36  2021-01-24 17:58:23  65.00000          0.00000             0.00000     8
32   5.00000 2021-02-01 19:27:59  2021-02-01 12:08:22   1.00000          0.00000             0.00000     8
33   4.50000 2021-02-01 13:09:17  2021-02-01 11:14:17  10.00000          0.00000             0.00000     8
34   5.00000 2021-02-01 12:16:46  2021-02-01 06:15:18  40.00000          0.00000             0.00000     8
35   4.50000 2021-02-01 09:29:56  2021-01-29 08:29:31  15.00000          0.00000             0.00000     8
36   5.00000 2021-02-01 07:57:43  2020-11-22 16:09:36   1.00000          0.00000             0.00000     8
37   5.00000 2021-02-01 06:03:40  2021-01-30 10:23:03   1.00000          0.00000             0.00000     8
38   5.00000 2021-01-31 21:45:28  2021-01-31 21:29:47   1.00000          0.00000             0.00000     9
39   5.00000 2021-01-31 20:52:42  2019-11-18 11:37:06   0.00000          0.00000             0.00000     9
40   3.50000 2021-01-31 19:48:51  2020-12-21 16:29:26  20.00000          0.00000             0.00000     9
41   4.50000 2021-01-31 19:34:20  2021-01-07 23:14:52   5.00000          0.00000             0.00000     9
42   5.00000 2021-01-31 18:59:27  2021-01-13 09:37:26   5.00000          0.00000             0.00000     9
43   3.50000 2021-01-31 18:07:01  2021-01-25 10:17:43   1.00000          0.00000             0.00000     9
44   5.00000 2021-01-31 16:02:14  2021-01-06 10:56:43  35.00000          0.00000             0.00000     9
45   5.00000 2021-01-31 15:45:39  2021-01-30 12:58:11  15.00000          0.00000             0.00000     9
46   4.50000 2021-01-31 15:23:46  2019-09-26 09:11:42   1.00000          0.00000             0.00000     9
47   5.00000 2021-01-31 14:13:32  2021-01-31 11:01:52  10.00000          0.00000             0.00000     9
48   4.50000 2021-01-31 11:23:24  2021-01-18 20:24:40  20.00000          0.00000             0.00000     9
49   5.00000 2021-01-31 08:48:53  2020-04-05 03:00:25   5.00000          0.00000             0.00000     9
50   5.00000 2021-01-31 08:05:53  2020-06-19 09:33:06  15.00000          0.00000             0.00000     9
51   5.00000 2021-01-30 22:17:08  2020-12-20 14:12:51  15.00000          0.00000             0.00000    10
52   5.00000 2021-01-30 18:47:09  2020-12-02 13:50:48  10.00000          0.00000             0.00000    10
53   4.00000 2021-01-30 18:00:45  2021-01-30 15:57:15   5.00000          0.00000             0.00000    10
54   5.00000 2021-01-30 17:46:47  2020-12-11 18:14:02  15.00000          0.00000             0.00000    10
55   5.00000 2021-01-30 16:57:13  2021-01-25 21:45:33  25.00000          0.00000             0.00000    10
56   5.00000 2021-01-30 16:25:44  2020-12-19 14:24:20  10.00000          0.00000             0.00000    10
57   3.00000 2021-01-30 13:44:07  2021-01-30 13:29:10   5.00000          0.00000             0.00000    10
58   5.00000 2021-01-30 12:35:03  2021-01-29 15:04:39  20.00000          0.00000             0.00000    10
59   5.00000 2021-01-30 12:10:22  2021-01-08 13:01:12  10.00000          0.00000             0.00000    10
60   5.00000 2021-01-30 11:45:02  2020-10-01 22:02:51  10.00000          0.00000             0.00000    10
61   5.00000 2021-01-30 11:28:26  2021-01-28 11:56:46  25.00000          0.00000             0.00000    10
62   5.00000 2021-01-30 10:19:14  2021-01-27 17:39:07  10.00000          0.00000             0.00000    10
63   5.00000 2021-01-29 22:30:04  2021-01-25 11:14:11  12.00000          0.00000             0.00000    11
64   5.00000 2021-01-29 20:57:29  2021-01-25 12:44:46   5.00000          0.00000             0.00000    11
65   4.00000 2021-01-29 19:51:08  2021-01-29 15:07:15  10.00000          0.00000             0.00000    11
66   5.00000 2021-01-29 18:07:02  2020-10-21 14:07:39  15.00000          0.00000             0.00000    11
67   5.00000 2021-01-29 17:54:38  2021-01-24 19:57:27  40.00000          0.00000             0.00000    11
68   5.00000 2021-01-29 15:52:18  2021-01-29 14:50:13  10.00000          0.00000             0.00000    11
69   5.00000 2021-01-29 13:50:57  2021-01-25 12:33:50   5.00000          0.00000             0.00000    11
70   5.00000 2021-01-29 13:38:44  2020-11-18 12:17:20  25.00000          0.00000             0.00000    11
71   3.50000 2021-01-29 11:36:47  2021-01-29 07:34:41  10.00000          1.00000             0.00000    11
72   4.50000 2021-01-29 11:12:09  2021-01-29 10:48:00  30.00000          0.00000             0.00000    11
73   5.00000 2021-01-29 07:49:51  2020-12-24 09:02:22   1.00000          0.00000             0.00000    11
74   5.00000 2021-01-29 06:34:40  2020-12-11 15:27:55  25.00000          0.00000             0.00000    11
75   4.50000 2021-01-28 20:17:56  2020-08-21 05:03:49   5.00000          0.00000             0.00000    12
76   5.00000 2021-01-28 17:33:55  2020-12-16 16:24:54  10.00000          0.00000             0.00000    12
77   5.00000 2021-01-28 10:09:21  2021-01-27 08:43:49   1.00000          0.00000             0.00000    12
78   5.00000 2021-01-28 08:35:46  2020-12-01 15:11:04   5.00000          0.00000             0.00000    12
79   5.00000 2021-01-27 22:36:15  2021-01-25 12:45:43  25.00000          0.00000             0.00000    13
80   5.00000 2021-01-27 22:25:12  2021-01-01 16:29:47   1.00000          0.00000             0.00000    13
81   5.00000 2021-01-27 21:25:43  2021-01-22 13:20:49  50.00000          0.00000             0.00000    13
82   4.00000 2021-01-27 20:46:02  2021-01-27 20:29:57  35.00000          0.00000             0.00000    13
83   5.00000 2021-01-27 19:20:43  2020-12-21 14:59:05  15.00000          0.00000             0.00000    13
84   4.00000 2021-01-27 18:56:24  2021-01-21 18:29:24  20.00000          0.00000             0.00000    13
85   5.00000 2021-01-27 17:21:08  2021-01-19 16:25:49   5.00000          0.00000             0.00000    13
86   5.00000 2021-01-27 14:16:50  2020-02-27 18:19:16  30.00000          0.00000             0.00000    13
87   5.00000 2021-01-27 09:01:39  2021-01-20 15:02:50  20.00000          0.00000             0.00000    13
88   5.00000 2021-01-27 07:19:53  2021-01-05 08:30:51  20.00000          0.00000             0.00000    13
89   4.50000 2021-01-26 20:35:29  2021-01-26 14:48:57  15.00000          1.00000             0.00000    14
90   5.00000 2021-01-26 20:31:50  2019-11-16 07:51:59  45.00000          0.00000             0.00000    14
91   5.00000 2021-01-26 18:21:17  2020-12-01 19:33:38  30.00000          0.00000             0.00000    14
92   5.00000 2021-01-26 12:46:00  2020-12-29 07:29:58   5.00000          0.00000             0.00000    14
93   5.00000 2021-01-26 11:36:24  2020-01-08 12:52:26  40.00000          0.00000             0.00000    14
94   4.00000 2021-01-26 11:10:07  2020-11-05 11:06:13  15.00000          0.00000             0.00000    14
95   5.00000 2021-01-26 11:06:34  2021-01-01 11:27:34  20.00000          0.00000             0.00000    14
96   5.00000 2021-01-26 09:16:21  2020-11-30 19:35:46   1.00000          0.00000             0.00000    14
97   2.00000 2021-01-26 07:56:03  2020-03-23 16:51:55   5.00000          0.00000             0.00000    14
98   5.00000 2021-01-25 17:32:32  2020-12-24 17:13:40   5.00000          0.00000             0.00000    15
99   4.50000 2021-01-25 15:09:45  2021-01-25 07:29:07  50.00000          0.00000             0.00000    15
100  5.00000 2021-01-25 10:39:05  2021-01-24 22:35:42   5.00000          0.00000             0.00000    15
101  5.00000 2021-01-24 18:47:59  2020-03-19 20:57:23   5.00000          0.00000             0.00000    16
102  5.00000 2021-01-24 15:14:33  2019-05-30 07:59:23  15.00000          0.00000             0.00000    16
103  4.50000 2021-01-24 14:03:11  2021-01-01 16:46:36   5.00000          0.00000             0.00000    16
104  5.00000 2021-01-24 12:46:01  2021-01-04 18:28:21  30.00000          0.00000             0.00000    16
105  4.00000 2021-01-24 12:28:11  2021-01-24 08:25:55  15.00000          0.00000             0.00000    16
106  5.00000 2021-01-24 10:51:47  2020-12-29 20:02:35  15.00000          0.00000             0.00000    16
107  5.00000 2021-01-24 08:43:13  2020-12-02 07:32:55  50.00000          0.00000             0.00000    16
108  4.50000 2021-01-23 22:44:03  2020-04-05 11:02:47  35.00000          0.00000             0.00000    17
109  4.50000 2021-01-23 19:24:26  2020-12-31 21:38:12   1.00000          0.00000             0.00000    17
110  5.00000 2021-01-23 18:57:28  2021-01-23 12:43:47  25.00000          0.00000             0.00000    17
111  5.00000 2021-01-23 17:46:26  2021-01-14 19:11:17  20.00000          0.00000             0.00000    17
112  5.00000 2021-01-22 19:11:38  2020-12-04 17:17:47  80.00000          1.00000             2.00000    18
113  4.00000 2021-01-22 09:08:13  2021-01-21 09:33:33   5.00000          0.00000             0.00000    18
114  5.00000 2021-01-22 08:08:05  2021-01-19 07:14:58   5.00000          0.00000             0.00000    18
115  5.00000 2021-01-21 22:11:40  2020-01-09 19:10:29  10.00000          0.00000             0.00000    19
116  5.00000 2021-01-21 18:44:16  2021-01-20 09:42:12  25.00000          0.00000             0.00000    19
117  5.00000 2021-01-21 17:17:27  2020-05-01 15:14:45  30.00000          0.00000             0.00000    19
118  4.50000 2021-01-21 15:22:42  2021-01-21 08:55:44   1.00000          0.00000             0.00000    19
119  5.00000 2021-01-21 11:49:21  2021-01-20 05:30:17   5.00000          0.00000             0.00000    19
120  5.00000 2021-01-21 09:27:41  2021-01-03 20:18:04   5.00000          0.00000             0.00000    19
121  5.00000 2021-01-21 08:46:45  2021-01-20 15:22:05  15.00000          0.00000             0.00000    19
122  5.00000 2021-01-21 05:41:13  2021-01-20 12:51:01  65.00000          0.00000             0.00000    19
123  5.00000 2021-01-20 20:00:20  2021-01-06 18:57:09  15.00000          0.00000             0.00000    20
124  4.50000 2021-01-20 19:50:41  2020-11-21 14:15:10  10.00000          0.00000             0.00000    20
125  5.00000 2021-01-20 18:37:29  2021-01-20 01:30:36  20.00000          0.00000             0.00000    20
126  5.00000 2021-01-20 17:12:19  2019-06-04 11:16:37   0.00000          0.00000             0.00000    20
127  5.00000 2021-01-19 22:56:44  2020-09-14 17:31:02  30.00000          0.00000             0.00000    21
128  5.00000 2021-01-19 16:50:09  2020-12-03 06:38:25  15.00000          0.00000             0.00000    21
129  5.00000 2021-01-19 14:27:28  2020-12-15 13:47:25  20.00000          0.00000             0.00000    21
130  5.00000 2021-01-19 11:03:03  2021-01-19 10:39:32   1.00000          0.00000             0.00000    21
131  5.00000 2021-01-19 10:14:39  2021-01-14 11:26:58  10.00000          0.00000             0.00000    21
132  3.50000 2021-01-19 01:29:01  2021-01-08 12:41:54  10.00000          0.00000             0.00000    21
133  5.00000 2021-01-18 23:19:50  2020-04-05 09:22:46   1.00000          0.00000             0.00000    22
134  5.00000 2021-01-18 21:09:08  2021-01-17 20:11:03  10.00000          0.00000             0.00000    22
135  5.00000 2021-01-17 22:33:40  2019-11-13 12:05:03  10.00000          0.00000             0.00000    23
136  5.00000 2021-01-17 22:22:24  2020-12-26 13:25:30   1.00000          0.00000             0.00000    23
137  5.00000 2021-01-17 19:45:29  2021-01-08 12:29:06  20.00000          0.00000             0.00000    23
138  5.00000 2021-01-17 19:09:36  2021-01-15 08:00:12  60.00000          0.00000             0.00000    23
139  5.00000 2021-01-17 18:39:44  2021-01-02 17:04:13  30.00000          0.00000             0.00000    23
140  5.00000 2021-01-17 17:35:20  2021-01-15 10:03:31  35.00000          0.00000             0.00000    23
141  4.50000 2021-01-17 14:35:23  2021-01-05 19:25:51  10.00000          0.00000             0.00000    23
142  5.00000 2021-01-17 14:24:30  2021-01-05 20:51:18  15.00000          1.00000             0.00000    23
143  5.00000 2021-01-17 12:24:18  2021-01-17 06:54:32  45.00000          0.00000             0.00000    23
144  4.50000 2021-01-17 11:13:09  2021-01-13 18:17:40   5.00000          0.00000             0.00000    23
145  5.00000 2021-01-17 10:52:33  2021-01-16 11:51:13   5.00000          0.00000             0.00000    23
146  5.00000 2021-01-17 03:29:40  2020-11-25 23:25:34  30.00000          0.00000             0.00000    23
147  5.00000 2021-01-17 00:04:38  2020-12-26 17:57:07   1.00000          0.00000             0.00000    23
148  5.00000 2021-01-16 22:22:44  2021-01-08 20:58:17   1.00000          0.00000             0.00000    24
149  5.00000 2021-01-16 22:16:16  2020-12-26 13:25:21  20.00000          0.00000             0.00000    24
150  5.00000 2021-01-16 17:43:14  2020-01-09 08:29:43  35.00000          0.00000             0.00000    24
151  5.00000 2021-01-16 16:57:18  2021-01-15 19:43:44  10.00000          0.00000             0.00000    24
152  5.00000 2021-01-16 16:49:29  2021-01-16 16:08:01  10.00000          2.00000             0.00000    24
153  5.00000 2021-01-16 14:54:39  2020-11-29 19:47:39  15.00000          0.00000             0.00000    24
154  4.00000 2021-01-16 13:54:39  2021-01-16 13:43:15  30.00000          0.00000             0.00000    24
155  4.00000 2021-01-16 13:36:37  2021-01-16 11:13:02   5.00000          0.00000             0.00000    24
156  5.00000 2021-01-16 13:02:42  2021-01-13 06:03:42   5.00000          0.00000             0.00000    24
157  5.00000 2021-01-16 12:33:22  2021-01-12 09:50:58  15.00000          0.00000             0.00000    24
158  4.50000 2021-01-16 11:17:22  2020-12-03 16:58:41   1.00000          0.00000             0.00000    24
159  5.00000 2021-01-16 08:44:28  2019-11-23 18:30:38  35.00000          0.00000             1.00000    24
160  4.50000 2021-01-15 22:51:07  2020-10-06 20:33:46  10.00000          0.00000             0.00000    25
161  5.00000 2021-01-15 20:34:11  2021-01-08 10:40:17  20.00000          0.00000             0.00000    25
162  5.00000 2021-01-15 18:47:51  2021-01-06 21:16:57   5.00000          0.00000             0.00000    25
163  5.00000 2021-01-15 18:05:05  2021-01-15 14:56:01   1.00000          0.00000             0.00000    25
164  5.00000 2021-01-15 15:19:00  2020-12-18 18:38:20  10.00000          0.00000             0.00000    25
165  5.00000 2021-01-14 21:26:27  2021-01-12 09:08:10  10.00000          0.00000             0.00000    26
166  5.00000 2021-01-14 14:03:14  2020-12-22 11:43:45  30.00000          0.00000             0.00000    26
167  4.50000 2021-01-13 21:49:32  2019-11-27 14:10:04 100.00000          2.00000             1.00000    27
168  4.00000 2021-01-13 12:16:51  2021-01-12 08:58:53  20.00000          0.00000             0.00000    27
169  5.00000 2021-01-13 09:15:07  2020-08-28 11:12:39   0.00000          0.00000             0.00000    27
170  5.00000 2021-01-13 06:49:33  2021-01-13 06:26:26  20.00000          0.00000             0.00000    27
171  5.00000 2021-01-13 00:22:06  2019-05-30 22:33:09   1.00000          0.00000             0.00000    27
172  5.00000 2021-01-12 19:25:14  2021-01-12 19:09:54  10.00000          0.00000             0.00000    28
173  3.00000 2021-01-12 11:21:08  2020-10-22 09:34:15   1.00000          0.00000             0.00000    28
174  5.00000 2021-01-12 09:51:38  2020-11-23 18:10:54 100.00000          0.00000             0.00000    28
175  5.00000 2021-01-12 05:29:55  2020-09-16 17:43:06  20.00000          0.00000             0.00000    28
176  4.00000 2021-01-12 04:01:50  2020-09-26 13:20:49  25.00000          0.00000             0.00000    28
177  5.00000 2021-01-11 22:49:08  2021-01-11 22:25:12   1.00000          0.00000             0.00000    29
178  5.00000 2021-01-11 22:17:47  2020-08-17 16:31:53   1.00000          0.00000             0.00000    29
179  4.50000 2021-01-11 20:42:42  2021-01-10 12:10:42  10.00000          0.00000             0.00000    29
180  4.50000 2021-01-11 20:31:28  2021-01-09 15:26:27   5.00000          0.00000             0.00000    29
181  5.00000 2021-01-11 20:02:33  2021-01-05 10:40:38   1.00000          0.00000             0.00000    29
182  5.00000 2021-01-11 17:04:13  2020-12-06 10:26:46 100.00000          0.00000             0.00000    29
183  5.00000 2021-01-11 14:06:01  2021-01-11 05:14:47   1.00000          0.00000             0.00000    29
184  4.50000 2021-01-11 13:18:31  2021-01-05 11:32:42  30.00000          1.00000             0.00000    29

In [104]:

# Bugünün tarihini belirleyin
current_date = pd.to_datetime('2021-02-10 0:0:0')

# Tüm yorumların tarihlerinden bugünün tarihini çıkararak gün cinsinden ifade edin
df["days"] = (current_date - df["Timestamp"]).dt.days

# Yeni 'days' adında bir sütun oluşturduk, bu sütunda her yorumun bugüne kadar kaç gün önce yapıldığını gösterir

# DataFrame'i görüntüleyerek değişiklikleri doğrulayın
print("DataFrame after calculating 'days' since comments were made:")
print(df)

DataFrame after calculating 'days' since comments were made:
      Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  days
0    5.00000 2021-02-05 07:45:55  2021-01-25 15:12:08   5.00000          0.00000             0.00000     4
1    5.00000 2021-02-04 21:05:32  2021-02-04 20:43:40   1.00000          0.00000             0.00000     5
2    4.50000 2021-02-04 20:34:03  2019-07-04 23:23:27   1.00000          0.00000             0.00000     5
3    5.00000 2021-02-04 16:56:28  2021-02-04 14:41:29  10.00000          0.00000             0.00000     5
4    4.00000 2021-02-04 15:00:24  2020-10-13 03:10:07  10.00000          0.00000             0.00000     5
5    4.00000 2021-02-04 12:42:36  2021-02-01 15:40:13   1.00000          0.00000             0.00000     5
6    5.00000 2021-02-04 12:25:30  2020-11-30 19:23:54  85.00000          0.00000             4.00000     5
7    4.50000 2021-02-04 11:13:15  2021-01-08 08:05:42  10.00000          0.00000             0.00000     5
8    5.00000 2021-02-04 08:59:53  2021-02-02 18:14:49   1.00000          0.00000             0.00000     5
9    5.00000 2021-02-03 22:40:04  2020-08-01 22:30:42  35.00000          0.00000             0.00000     6
10   5.00000 2021-02-03 21:26:02  2021-02-01 09:54:49   5.00000          0.00000             0.00000     6
11   5.00000 2021-02-03 21:14:25  2021-02-01 18:45:00   1.00000          0.00000             0.00000     6
12   5.00000 2021-02-03 20:55:19  2021-02-03 20:00:04  10.00000          0.00000             0.00000     6
13   3.00000 2021-02-03 19:16:45  2021-02-03 18:42:21   1.00000          0.00000             0.00000     6
14   5.00000 2021-02-03 19:08:33  2020-03-29 09:07:41  93.00000          1.00000             0.00000     6
15   5.00000 2021-02-03 18:57:11  2020-03-19 19:28:43   1.00000          0.00000             0.00000     6
16   2.50000 2021-02-03 18:56:58  2021-02-01 09:23:31   5.00000          0.00000             0.00000     6
17   5.00000 2021-02-03 17:21:45  2021-01-28 20:46:12   5.00000          0.00000             0.00000     6
18   5.00000 2021-02-03 17:12:26  2019-07-25 08:04:26  35.00000          0.00000             0.00000     6
19   5.00000 2021-02-03 16:13:36  2021-02-02 07:15:55   5.00000          0.00000             0.00000     6
20   4.00000 2021-02-02 23:55:23  2021-02-02 17:47:41   1.00000          0.00000             0.00000     7
21   5.00000 2021-02-02 22:34:25  2021-01-19 22:29:49   5.00000          0.00000             0.00000     7
22   5.00000 2021-02-02 21:59:49  2021-01-03 19:42:39  35.00000          0.00000             0.00000     7
23   5.00000 2021-02-02 18:00:59  2021-01-27 13:11:18   1.00000          0.00000             0.00000     7
24   5.00000 2021-02-02 16:29:58  2021-02-02 16:10:52  15.00000          0.00000             0.00000     7
25   5.00000 2021-02-02 14:30:03  2020-04-04 22:14:15  25.00000          0.00000             0.00000     7
26   5.00000 2021-02-02 12:54:25  2021-02-02 09:07:03  15.00000          0.00000             0.00000     7
27   5.00000 2021-02-02 12:02:59  2020-09-20 12:26:30   1.00000          0.00000             0.00000     7
28   5.00000 2021-02-02 11:58:42  2021-02-02 10:07:22  20.00000          0.00000             0.00000     7
29   5.00000 2021-02-02 10:47:54  2020-08-20 19:14:01   5.00000          0.00000             0.00000     7
30   5.00000 2021-02-02 04:58:56  2021-01-31 14:58:49  15.00000          0.00000             0.00000     7
31   5.00000 2021-02-01 21:27:36  2021-01-24 17:58:23  65.00000          0.00000             0.00000     8
32   5.00000 2021-02-01 19:27:59  2021-02-01 12:08:22   1.00000          0.00000             0.00000     8
33   4.50000 2021-02-01 13:09:17  2021-02-01 11:14:17  10.00000          0.00000             0.00000     8
34   5.00000 2021-02-01 12:16:46  2021-02-01 06:15:18  40.00000          0.00000             0.00000     8
35   4.50000 2021-02-01 09:29:56  2021-01-29 08:29:31  15.00000          0.00000             0.00000     8
36   5.00000 2021-02-01 07:57:43  2020-11-22 16:09:36   1.00000          0.00000             0.00000     8
37   5.00000 2021-02-01 06:03:40  2021-01-30 10:23:03   1.00000          0.00000             0.00000     8
38   5.00000 2021-01-31 21:45:28  2021-01-31 21:29:47   1.00000          0.00000             0.00000     9
39   5.00000 2021-01-31 20:52:42  2019-11-18 11:37:06   0.00000          0.00000             0.00000     9
40   3.50000 2021-01-31 19:48:51  2020-12-21 16:29:26  20.00000          0.00000             0.00000     9
41   4.50000 2021-01-31 19:34:20  2021-01-07 23:14:52   5.00000          0.00000             0.00000     9
42   5.00000 2021-01-31 18:59:27  2021-01-13 09:37:26   5.00000          0.00000             0.00000     9
43   3.50000 2021-01-31 18:07:01  2021-01-25 10:17:43   1.00000          0.00000             0.00000     9
44   5.00000 2021-01-31 16:02:14  2021-01-06 10:56:43  35.00000          0.00000             0.00000     9
45   5.00000 2021-01-31 15:45:39  2021-01-30 12:58:11  15.00000          0.00000             0.00000     9
46   4.50000 2021-01-31 15:23:46  2019-09-26 09:11:42   1.00000          0.00000             0.00000     9
47   5.00000 2021-01-31 14:13:32  2021-01-31 11:01:52  10.00000          0.00000             0.00000     9
48   4.50000 2021-01-31 11:23:24  2021-01-18 20:24:40  20.00000          0.00000             0.00000     9
49   5.00000 2021-01-31 08:48:53  2020-04-05 03:00:25   5.00000          0.00000             0.00000     9
50   5.00000 2021-01-31 08:05:53  2020-06-19 09:33:06  15.00000          0.00000             0.00000     9
51   5.00000 2021-01-30 22:17:08  2020-12-20 14:12:51  15.00000          0.00000             0.00000    10
52   5.00000 2021-01-30 18:47:09  2020-12-02 13:50:48  10.00000          0.00000             0.00000    10
53   4.00000 2021-01-30 18:00:45  2021-01-30 15:57:15   5.00000          0.00000             0.00000    10
54   5.00000 2021-01-30 17:46:47  2020-12-11 18:14:02  15.00000          0.00000             0.00000    10
55   5.00000 2021-01-30 16:57:13  2021-01-25 21:45:33  25.00000          0.00000             0.00000    10
56   5.00000 2021-01-30 16:25:44  2020-12-19 14:24:20  10.00000          0.00000             0.00000    10
57   3.00000 2021-01-30 13:44:07  2021-01-30 13:29:10   5.00000          0.00000             0.00000    10
58   5.00000 2021-01-30 12:35:03  2021-01-29 15:04:39  20.00000          0.00000             0.00000    10
59   5.00000 2021-01-30 12:10:22  2021-01-08 13:01:12  10.00000          0.00000             0.00000    10
60   5.00000 2021-01-30 11:45:02  2020-10-01 22:02:51  10.00000          0.00000             0.00000    10
61   5.00000 2021-01-30 11:28:26  2021-01-28 11:56:46  25.00000          0.00000             0.00000    10
62   5.00000 2021-01-30 10:19:14  2021-01-27 17:39:07  10.00000          0.00000             0.00000    10
63   5.00000 2021-01-29 22:30:04  2021-01-25 11:14:11  12.00000          0.00000             0.00000    11
64   5.00000 2021-01-29 20:57:29  2021-01-25 12:44:46   5.00000          0.00000             0.00000    11
65   4.00000 2021-01-29 19:51:08  2021-01-29 15:07:15  10.00000          0.00000             0.00000    11
66   5.00000 2021-01-29 18:07:02  2020-10-21 14:07:39  15.00000          0.00000             0.00000    11
67   5.00000 2021-01-29 17:54:38  2021-01-24 19:57:27  40.00000          0.00000             0.00000    11
68   5.00000 2021-01-29 15:52:18  2021-01-29 14:50:13  10.00000          0.00000             0.00000    11
69   5.00000 2021-01-29 13:50:57  2021-01-25 12:33:50   5.00000          0.00000             0.00000    11
70   5.00000 2021-01-29 13:38:44  2020-11-18 12:17:20  25.00000          0.00000             0.00000    11
71   3.50000 2021-01-29 11:36:47  2021-01-29 07:34:41  10.00000          1.00000             0.00000    11
72   4.50000 2021-01-29 11:12:09  2021-01-29 10:48:00  30.00000          0.00000             0.00000    11
73   5.00000 2021-01-29 07:49:51  2020-12-24 09:02:22   1.00000          0.00000             0.00000    11
74   5.00000 2021-01-29 06:34:40  2020-12-11 15:27:55  25.00000          0.00000             0.00000    11
75   4.50000 2021-01-28 20:17:56  2020-08-21 05:03:49   5.00000          0.00000             0.00000    12
76   5.00000 2021-01-28 17:33:55  2020-12-16 16:24:54  10.00000          0.00000             0.00000    12
77   5.00000 2021-01-28 10:09:21  2021-01-27 08:43:49   1.00000          0.00000             0.00000    12
78   5.00000 2021-01-28 08:35:46  2020-12-01 15:11:04   5.00000          0.00000             0.00000    12
79   5.00000 2021-01-27 22:36:15  2021-01-25 12:45:43  25.00000          0.00000             0.00000    13
80   5.00000 2021-01-27 22:25:12  2021-01-01 16:29:47   1.00000          0.00000             0.00000    13
81   5.00000 2021-01-27 21:25:43  2021-01-22 13:20:49  50.00000          0.00000             0.00000    13
82   4.00000 2021-01-27 20:46:02  2021-01-27 20:29:57  35.00000          0.00000             0.00000    13
83   5.00000 2021-01-27 19:20:43  2020-12-21 14:59:05  15.00000          0.00000             0.00000    13
84   4.00000 2021-01-27 18:56:24  2021-01-21 18:29:24  20.00000          0.00000             0.00000    13
85   5.00000 2021-01-27 17:21:08  2021-01-19 16:25:49   5.00000          0.00000             0.00000    13
86   5.00000 2021-01-27 14:16:50  2020-02-27 18:19:16  30.00000          0.00000             0.00000    13
87   5.00000 2021-01-27 09:01:39  2021-01-20 15:02:50  20.00000          0.00000             0.00000    13
88   5.00000 2021-01-27 07:19:53  2021-01-05 08:30:51  20.00000          0.00000             0.00000    13
89   4.50000 2021-01-26 20:35:29  2021-01-26 14:48:57  15.00000          1.00000             0.00000    14
90   5.00000 2021-01-26 20:31:50  2019-11-16 07:51:59  45.00000          0.00000             0.00000    14
91   5.00000 2021-01-26 18:21:17  2020-12-01 19:33:38  30.00000          0.00000             0.00000    14
92   5.00000 2021-01-26 12:46:00  2020-12-29 07:29:58   5.00000          0.00000             0.00000    14
93   5.00000 2021-01-26 11:36:24  2020-01-08 12:52:26  40.00000          0.00000             0.00000    14
94   4.00000 2021-01-26 11:10:07  2020-11-05 11:06:13  15.00000          0.00000             0.00000    14
95   5.00000 2021-01-26 11:06:34  2021-01-01 11:27:34  20.00000          0.00000             0.00000    14
96   5.00000 2021-01-26 09:16:21  2020-11-30 19:35:46   1.00000          0.00000             0.00000    14
97   2.00000 2021-01-26 07:56:03  2020-03-23 16:51:55   5.00000          0.00000             0.00000    14
98   5.00000 2021-01-25 17:32:32  2020-12-24 17:13:40   5.00000          0.00000             0.00000    15
99   4.50000 2021-01-25 15:09:45  2021-01-25 07:29:07  50.00000          0.00000             0.00000    15
100  5.00000 2021-01-25 10:39:05  2021-01-24 22:35:42   5.00000          0.00000             0.00000    15
101  5.00000 2021-01-24 18:47:59  2020-03-19 20:57:23   5.00000          0.00000             0.00000    16
102  5.00000 2021-01-24 15:14:33  2019-05-30 07:59:23  15.00000          0.00000             0.00000    16
103  4.50000 2021-01-24 14:03:11  2021-01-01 16:46:36   5.00000          0.00000             0.00000    16
104  5.00000 2021-01-24 12:46:01  2021-01-04 18:28:21  30.00000          0.00000             0.00000    16
105  4.00000 2021-01-24 12:28:11  2021-01-24 08:25:55  15.00000          0.00000             0.00000    16
106  5.00000 2021-01-24 10:51:47  2020-12-29 20:02:35  15.00000          0.00000             0.00000    16
107  5.00000 2021-01-24 08:43:13  2020-12-02 07:32:55  50.00000          0.00000             0.00000    16
108  4.50000 2021-01-23 22:44:03  2020-04-05 11:02:47  35.00000          0.00000             0.00000    17
109  4.50000 2021-01-23 19:24:26  2020-12-31 21:38:12   1.00000          0.00000             0.00000    17
110  5.00000 2021-01-23 18:57:28  2021-01-23 12:43:47  25.00000          0.00000             0.00000    17
111  5.00000 2021-01-23 17:46:26  2021-01-14 19:11:17  20.00000          0.00000             0.00000    17
112  5.00000 2021-01-22 19:11:38  2020-12-04 17:17:47  80.00000          1.00000             2.00000    18
113  4.00000 2021-01-22 09:08:13  2021-01-21 09:33:33   5.00000          0.00000             0.00000    18
114  5.00000 2021-01-22 08:08:05  2021-01-19 07:14:58   5.00000          0.00000             0.00000    18
115  5.00000 2021-01-21 22:11:40  2020-01-09 19:10:29  10.00000          0.00000             0.00000    19
116  5.00000 2021-01-21 18:44:16  2021-01-20 09:42:12  25.00000          0.00000             0.00000    19
117  5.00000 2021-01-21 17:17:27  2020-05-01 15:14:45  30.00000          0.00000             0.00000    19
118  4.50000 2021-01-21 15:22:42  2021-01-21 08:55:44   1.00000          0.00000             0.00000    19
119  5.00000 2021-01-21 11:49:21  2021-01-20 05:30:17   5.00000          0.00000             0.00000    19
120  5.00000 2021-01-21 09:27:41  2021-01-03 20:18:04   5.00000          0.00000             0.00000    19
121  5.00000 2021-01-21 08:46:45  2021-01-20 15:22:05  15.00000          0.00000             0.00000    19
122  5.00000 2021-01-21 05:41:13  2021-01-20 12:51:01  65.00000          0.00000             0.00000    19
123  5.00000 2021-01-20 20:00:20  2021-01-06 18:57:09  15.00000          0.00000             0.00000    20
124  4.50000 2021-01-20 19:50:41  2020-11-21 14:15:10  10.00000          0.00000             0.00000    20
125  5.00000 2021-01-20 18:37:29  2021-01-20 01:30:36  20.00000          0.00000             0.00000    20
126  5.00000 2021-01-20 17:12:19  2019-06-04 11:16:37   0.00000          0.00000             0.00000    20
127  5.00000 2021-01-19 22:56:44  2020-09-14 17:31:02  30.00000          0.00000             0.00000    21
128  5.00000 2021-01-19 16:50:09  2020-12-03 06:38:25  15.00000          0.00000             0.00000    21
129  5.00000 2021-01-19 14:27:28  2020-12-15 13:47:25  20.00000          0.00000             0.00000    21
130  5.00000 2021-01-19 11:03:03  2021-01-19 10:39:32   1.00000          0.00000             0.00000    21
131  5.00000 2021-01-19 10:14:39  2021-01-14 11:26:58  10.00000          0.00000             0.00000    21
132  3.50000 2021-01-19 01:29:01  2021-01-08 12:41:54  10.00000          0.00000             0.00000    21
133  5.00000 2021-01-18 23:19:50  2020-04-05 09:22:46   1.00000          0.00000             0.00000    22
134  5.00000 2021-01-18 21:09:08  2021-01-17 20:11:03  10.00000          0.00000             0.00000    22
135  5.00000 2021-01-17 22:33:40  2019-11-13 12:05:03  10.00000          0.00000             0.00000    23
136  5.00000 2021-01-17 22:22:24  2020-12-26 13:25:30   1.00000          0.00000             0.00000    23
137  5.00000 2021-01-17 19:45:29  2021-01-08 12:29:06  20.00000          0.00000             0.00000    23
138  5.00000 2021-01-17 19:09:36  2021-01-15 08:00:12  60.00000          0.00000             0.00000    23
139  5.00000 2021-01-17 18:39:44  2021-01-02 17:04:13  30.00000          0.00000             0.00000    23
140  5.00000 2021-01-17 17:35:20  2021-01-15 10:03:31  35.00000          0.00000             0.00000    23
141  4.50000 2021-01-17 14:35:23  2021-01-05 19:25:51  10.00000          0.00000             0.00000    23
142  5.00000 2021-01-17 14:24:30  2021-01-05 20:51:18  15.00000          1.00000             0.00000    23
143  5.00000 2021-01-17 12:24:18  2021-01-17 06:54:32  45.00000          0.00000             0.00000    23
144  4.50000 2021-01-17 11:13:09  2021-01-13 18:17:40   5.00000          0.00000             0.00000    23
145  5.00000 2021-01-17 10:52:33  2021-01-16 11:51:13   5.00000          0.00000             0.00000    23
146  5.00000 2021-01-17 03:29:40  2020-11-25 23:25:34  30.00000          0.00000             0.00000    23
147  5.00000 2021-01-17 00:04:38  2020-12-26 17:57:07   1.00000          0.00000             0.00000    23
148  5.00000 2021-01-16 22:22:44  2021-01-08 20:58:17   1.00000          0.00000             0.00000    24
149  5.00000 2021-01-16 22:16:16  2020-12-26 13:25:21  20.00000          0.00000             0.00000    24
150  5.00000 2021-01-16 17:43:14  2020-01-09 08:29:43  35.00000          0.00000             0.00000    24
151  5.00000 2021-01-16 16:57:18  2021-01-15 19:43:44  10.00000          0.00000             0.00000    24
152  5.00000 2021-01-16 16:49:29  2021-01-16 16:08:01  10.00000          2.00000             0.00000    24
153  5.00000 2021-01-16 14:54:39  2020-11-29 19:47:39  15.00000          0.00000             0.00000    24
154  4.00000 2021-01-16 13:54:39  2021-01-16 13:43:15  30.00000          0.00000             0.00000    24
155  4.00000 2021-01-16 13:36:37  2021-01-16 11:13:02   5.00000          0.00000             0.00000    24
156  5.00000 2021-01-16 13:02:42  2021-01-13 06:03:42   5.00000          0.00000             0.00000    24
157  5.00000 2021-01-16 12:33:22  2021-01-12 09:50:58  15.00000          0.00000             0.00000    24
158  4.50000 2021-01-16 11:17:22  2020-12-03 16:58:41   1.00000          0.00000             0.00000    24
159  5.00000 2021-01-16 08:44:28  2019-11-23 18:30:38  35.00000          0.00000             1.00000    24
160  4.50000 2021-01-15 22:51:07  2020-10-06 20:33:46  10.00000          0.00000             0.00000    25
161  5.00000 2021-01-15 20:34:11  2021-01-08 10:40:17  20.00000          0.00000             0.00000    25
162  5.00000 2021-01-15 18:47:51  2021-01-06 21:16:57   5.00000          0.00000             0.00000    25
163  5.00000 2021-01-15 18:05:05  2021-01-15 14:56:01   1.00000          0.00000             0.00000    25
164  5.00000 2021-01-15 15:19:00  2020-12-18 18:38:20  10.00000          0.00000             0.00000    25
165  5.00000 2021-01-14 21:26:27  2021-01-12 09:08:10  10.00000          0.00000             0.00000    26
166  5.00000 2021-01-14 14:03:14  2020-12-22 11:43:45  30.00000          0.00000             0.00000    26
167  4.50000 2021-01-13 21:49:32  2019-11-27 14:10:04 100.00000          2.00000             1.00000    27
168  4.00000 2021-01-13 12:16:51  2021-01-12 08:58:53  20.00000          0.00000             0.00000    27
169  5.00000 2021-01-13 09:15:07  2020-08-28 11:12:39   0.00000          0.00000             0.00000    27
170  5.00000 2021-01-13 06:49:33  2021-01-13 06:26:26  20.00000          0.00000             0.00000    27
171  5.00000 2021-01-13 00:22:06  2019-05-30 22:33:09   1.00000          0.00000             0.00000    27
172  5.00000 2021-01-12 19:25:14  2021-01-12 19:09:54  10.00000          0.00000             0.00000    28
173  3.00000 2021-01-12 11:21:08  2020-10-22 09:34:15   1.00000          0.00000             0.00000    28
174  5.00000 2021-01-12 09:51:38  2020-11-23 18:10:54 100.00000          0.00000             0.00000    28
175  5.00000 2021-01-12 05:29:55  2020-09-16 17:43:06  20.00000          0.00000             0.00000    28
176  4.00000 2021-01-12 04:01:50  2020-09-26 13:20:49  25.00000          0.00000             0.00000    28
177  5.00000 2021-01-11 22:49:08  2021-01-11 22:25:12   1.00000          0.00000             0.00000    29
178  5.00000 2021-01-11 22:17:47  2020-08-17 16:31:53   1.00000          0.00000             0.00000    29
179  4.50000 2021-01-11 20:42:42  2021-01-10 12:10:42  10.00000          0.00000             0.00000    29
180  4.50000 2021-01-11 20:31:28  2021-01-09 15:26:27   5.00000          0.00000             0.00000    29
181  5.00000 2021-01-11 20:02:33  2021-01-05 10:40:38   1.00000          0.00000             0.00000    29
182  5.00000 2021-01-11 17:04:13  2020-12-06 10:26:46 100.00000          0.00000             0.00000    29
183  5.00000 2021-01-11 14:06:01  2021-01-11 05:14:47   1.00000          0.00000             0.00000    29
184  4.50000 2021-01-11 13:18:31  2021-01-05 11:32:42  30.00000          1.00000             0.00000    29

In [105]:
# "days" sütununda değeri 30 günden küçük veya eşit olan satırları filtreleyerek, bu satırların "Rating" sütununun ortalamasını alır.
df.loc[df["days"] <= 30, "Rating"].mean()

4.775773195876289

In [106]:
df[df["days"] <= 30].count()

Rating                194
Timestamp             194
Enrolled              194
Progress              194
Questions Asked       194
Questions Answered    194
days                  194
dtype: int64

In [107]:
df.loc[df["days"] > 30, "Rating"] #son 30 gündeki Rate'ler geldi
df.loc[df["days"] > 30, "Rating"] .mean()

4.763744248001937

In [108]:
#30 günden fazla ve 90 günden az olan günlere bakıyoruz
df.loc[(df["days"] > 30) & (df["days"] <= 90), "Rating"].mean()

4.763833992094861

In [77]:
#eski tarihli günlere bamak istersek eğer:
df.loc[(df["days"] > 90) & (df["days"] <= 180), "Rating"].mean()

4.752503576537912

In [109]:
#demekki son zamanlarda kursun memnuniyeti ile ilgili bir artış var.
df.loc[(df["days"] > 180), "Rating"].mean()

4.76641586867305

In [110]:
# Son 30 günde yapılan yorumların ortalama puanını alarak %28'ini hesaplar.
# 30-90 gün arasındaki yorumların ortalama puanını alarak %26'sını hesaplar.
# 90-180 gün arasındaki yorumların ortalama puanını alarak %24'ünü hesaplar.
# 180 günden daha eski yorumların ortalama puanını alarak %22'sini hesaplar.
# Bu değerlerin toplamı 100'e eşit olmalıdır.
rate = (
    df.loc[df["days"] <= 30, "Rating"].mean() * 28/100 +
    df.loc[(df["days"] > 30) & (df["days"] <= 90), "Rating"].mean() * 26/100 +
    df.loc[(df["days"] > 90) & (df["days"] <= 180), "Rating"].mean() * 24/100 +
    df.loc[df["days"] > 180, "Rating"].mean() * 22/100
)

# Ağırlıklı ortalama puanı 'rate' değişkenine atar
rate

4.765025682267194

In [111]:
def time_based_weighted_average(dataframe, w1=28, w2=26, w3=24, w4=22):
    """
    Verilen DataFrame'deki yorumların tarihlerine dayalı olarak ağırlıklandırılmış bir ortalama puanı hesaplar.

    Parametreler:
    - dataframe: Değerlendirme verilerinin bulunduğu DataFrame
    - w1: Son 30 gün için kullanılacak ağırlık (varsayılan: 28)
    - w2: 30-90 gün arası için kullanılacak ağırlık (varsayılan: 26)
    - w3: 90-180 gün arası için kullanılacak ağırlık (varsayılan: 24)
    - w4: 180 günden daha eski yorumlar için kullanılacak ağırlık (varsayılan: 22)

    Dönüş Değeri:
    - Ağırlıklandırılmış ortalama puan
    """
    return dataframe.loc[dataframe["days"] <= 30, "Rating"].mean() * w1 / 100 + \
           dataframe.loc[(dataframe["days"] > 30) & (dataframe["days"] <= 90), "Rating"].mean() * w2 / 100 + \
           dataframe.loc[(dataframe["days"] > 90) & (dataframe["days"] <= 180), "Rating"].mean() * w3 / 100 + \
           dataframe.loc[(dataframe["days"] > 180), "Rating"].mean() * w4 / 100

In [112]:
time_based_weighted_average(df)

4.765025682267194

In [113]:
time_based_weighted_average(df, 30, 26, 22, 22)

4.765491074653962

In [114]:
def uniform_weighted_average(dataframe, weight=25):
    """
    Tüm yorumlar için aynı ağırlığı kullanarak bir ortalama puan hesaplar.

    Parametreler:
    - dataframe: Değerlendirme verilerinin bulunduğu DataFrame
    - weight: Tüm yorumlar için kullanılacak ağırlık (varsayılan: 25)

    Dönüş Değeri:
    - Ağırlıklandırılmış ortalama puan
    """
    return dataframe["Rating"].mean() * weight / 100

In [115]:
####################
# User-Based Weighted Average (kullanıcı temelli ağırlıklı ortalama)
####################

#user based=user quality

#acaba kursu izleme oranlarına göre daha farklı bir ağırlık mı olmalı?
df.head()

   Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  days
0 5.00000 2021-02-05 07:45:55  2021-01-25 15:12:08   5.00000          0.00000             0.00000     4
1 5.00000 2021-02-04 21:05:32  2021-02-04 20:43:40   1.00000          0.00000             0.00000     5
2 4.50000 2021-02-04 20:34:03  2019-07-04 23:23:27   1.00000          0.00000             0.00000     5
3 5.00000 2021-02-04 16:56:28  2021-02-04 14:41:29  10.00000          0.00000             0.00000     5
4 4.00000 2021-02-04 15:00:24  2020-10-13 03:10:07  10.00000          0.00000             0.00000     5

In [116]:
# Gruplama yaparak her bir ilerleme seviyesi için ortalama puanı hesaplayın
df.groupby("Progress").agg({"Rating": "mean"})

# İlerleme seviyesine göre ağırlıklandırılmış ortalama puanı hesaplayın
df.loc[df["Progress"] <= 10, "Rating"].mean() * 22 / 100 + \
    df.loc[(df["Progress"] > 10) & (df["Progress"] <= 45), "Rating"].mean() * 24 / 100 + \
    df.loc[(df["Progress"] > 45) & (df["Progress"] <= 75), "Rating"].mean() * 26 / 100 + \
    df.loc[df["Progress"] > 75, "Rating"].mean() * 28 / 100

4.800257704672543

In [117]:
def user_based_weighted_average(dataframe, w1=22, w2=24, w3=26, w4=28):
    """
    Her bir kullanıcının ilerleme seviyesine göre ağırlıklandırılmış bir ortalama puan hesaplar.

    Parametreler:
    - dataframe: Kullanıcıların ilerleme ve puanlama verilerinin bulunduğu DataFrame
    - w1: 10 veya daha az ilerleme seviyesi için kullanılacak ağırlık (varsayılan: 22)
    - w2: 10-45 arası ilerleme seviyesi için kullanılacak ağırlık (varsayılan: 24)
    - w3: 45-75 arası ilerleme seviyesi için kullanılacak ağırlık (varsayılan: 26)
    - w4: 75'ten daha fazla ilerleme seviyesi için kullanılacak ağırlık (varsayılan: 28)

    Dönüş Değeri:
    - Ağırlıklandırılmış ortalama puan
    """
    return dataframe.loc[dataframe["Progress"] <= 10, "Rating"].mean() * w1 / 100 + \
           dataframe.loc[(dataframe["Progress"] > 10) & (dataframe["Progress"] <= 45), "Rating"].mean() * w2 / 100 + \
           dataframe.loc[(dataframe["Progress"] > 45) & (dataframe["Progress"] <= 75), "Rating"].mean() * w3 / 100 + \
           dataframe.loc[dataframe["Progress"] > 75, "Rating"].mean() * w4 / 100

In [118]:
user_based_weighted_average(df, 20, 24, 26, 30)

4.803286469062915

In [119]:
####################
# Weighted Rating (time based + user base) bir araya getirilerek ağırlıklandırma çalışması
####################

In [120]:
def course_weighted_rating(dataframe, time_w=50, user_w=50):
    """
    Zaman ve kullanıcı bazında ağırlıklandırılmış bir ortalama puan hesaplar.

    Parametreler:
    - dataframe: Kullanıcıların ilerleme ve puanlama verilerinin bulunduğu DataFrame
    - time_w: Zaman bazında kullanılacak ağırlık (varsayılan: 50)
    - user_w: Kullanıcı bazında kullanılacak ağırlık (varsayılan: 50)

    Dönüş Değeri:
    - Zaman ve kullanıcı bazında ağırlıklandırılmış ortalama puan
    """
    return (time_based_weighted_average(dataframe) * time_w / 100) + \
           (user_based_weighted_average(dataframe) * user_w / 100)

In [121]:
course_weighted_rating(df)

4.782641693469868

In [122]:
course_weighted_rating(df, time_w=40, user_w=60)

4.786164895710403