# GroupBy Sorguları

In [20]:
import numpy as np
import pandas as pd

In [21]:
dataset = {
        "Departman":["Bilişim","İnsan Kaynakları","Üretim","Üretim","Bilişim","İnsan Kaynakları"],
        "Çalışan": ["Taner","Esra","Samir","Zeynep","Arda","Messi"],
        "Maaş":[3000,3500,2500,4500,4000,2000]
        }

In [22]:
dataset

{'Departman': ['Bilişim',
  'İnsan Kaynakları',
  'Üretim',
  'Üretim',
  'Bilişim',
  'İnsan Kaynakları'],
 'Çalışan': ['Taner', 'Esra', 'Samir', 'Zeynep', 'Arda', 'Messi'],
 'Maaş': [3000, 3500, 2500, 4500, 4000, 2000]}

In [23]:
df = pd.DataFrame(dataset)

In [24]:
df

          Departman Çalışan  Maaş
0           Bilişim   Taner  3000
1  İnsan Kaynakları    Esra  3500
2            Üretim   Samir  2500
3            Üretim  Zeynep  4500
4           Bilişim    Arda  4000
5  İnsan Kaynakları   Messi  2000

In [25]:
DepGroup = df.groupby("Departman")

In [26]:
DepGroup

In [27]:
DepGroup.sum()

                  Maaş
Departman
Bilişim           7000
Üretim            7000
İnsan Kaynakları  5500

In [28]:
TotalPriceB = DepGroup.sum().loc["Bilişim"]

In [29]:
TotalPriceB

Maaş    7000
Name: Bilişim, dtype: int64

In [30]:
int(TotalPriceB)

7000

In [31]:
df.groupby("Departman").count()

                  Çalışan  Maaş
Departman
Bilişim                 2     2
Üretim                  2     2
İnsan Kaynakları        2     2

In [32]:
df.groupby("Departman").max()

                 Çalışan  Maaş
Departman
Bilişim            Taner  4000
Üretim            Zeynep  4500
İnsan Kaynakları   Messi  3500

In [33]:
minPriceB = df.groupby("Departman").min()["Maaş"]["Bilişim"]

In [34]:
minPriceB

3000

In [35]:
averagePriceB = df.groupby("Departman").mean().loc["Bilişim"]["Maaş"]

In [36]:
averagePriceB

3500.0